/**
 * Antislop Language Support, Cliché Patterns, Dictionaries, and Tone Profiles
 * Formulated under Anti-Slop Copywriting & De-Detection Principles
 */

const LANGUAGES = {
    id: {
        name: "Bahasa Indonesia",
        flag: "🇮🇩",
        
        // Universal Antislop Cliché & Formulaic AI Patterns (De-Slop Rules R-16, R-36, R-02)
        cliches: [
            // 1. Em Dash Elimination (R-02)
            { pattern: /\s*—\s*/g, replacement: ", " },
            { pattern: /\s*--\s*/g, replacement: ", " },

            // 2. Elimination of AI Discourse Openers & Fillers (R-16, R-36)
            { pattern: /\b(?:tidak\s+dapat\s+dipungkiri|tak\s+dapat\s+dimungkiri|tidak\s+dapat\s+disangkal|tak\s+bisa\s+dipungkiri|sudah\s+tidak\s+bisa\s+dipungkiri)\s+bahwa,?\s*/gi, replacement: "" },
            { pattern: /\b(?:tidak\s+dapat\s+dipungkiri|tak\s+dapat\s+dimungkiri|tidak\s+dapat\s+disangkal|tak\s+bisa\s+dipungkiri)\b/gi, replacement: "" },
            { pattern: /\b(?:sebagaimana\s+(?:telah\s+)?kita\s+ketahui\s+bersama|seperti\s+yang\s+kita\s+ketahui|seperti\s+yang\s+telah\s+diketahui),?\s*/gi, replacement: "sebagaimana dipahami, " },
            { pattern: /\bsudah\s+bukan\s+rahasia\s+lagi\s+(?:bahwa)?,?\s*/gi, replacement: "jelas terlihat bahwa " },
            { pattern: /\b(?:dalam|di)\s+era\s+(?:digital|modern|globalisasi|transformasi\s+digital|informasi|teknologi)?\s*(?:yang\s+serba\s+cepat\s+)?(?:saat\s+ini|sekarang\s+ini|dewasa\s+ini|ini)?,?\s*/gi, replacement: "saat ini, " },
            { pattern: /\bdalam\s+era\s+(?:modern|digital)\b/gi, replacement: "saat ini" },
            { pattern: /\bera\s+modern\b/gi, replacement: "masa kini" },
            { pattern: /\bera\s+digital\b/gi, replacement: "ranah digital" },
            { pattern: /\bdi\s+tengah\s+(?:pesatnya\s+)?(?:perkembangan|kemajuan|laju)\s+(?:teknologi|zaman|digitalisasi),?\s*/gi, replacement: "di tengah pesatnya teknologi saat ini, " },
            { pattern: /\bdalam\s+lanskap\s+(?:bisnis|digital|teknologi|pendidikan)?\s*(?:yang\s+terus\s+berkembang|modern),?\s*/gi, replacement: "pada praktiknya saat ini, " },

            // 3. Filler Phrases & Signposting Elimination (Cut ceremony, keep content)
            { pattern: /\bdalam\s+rangka\s+(?:untuk|guna|mencapai)\b/gi, replacement: "guna" },
            { pattern: /\bperlu\s+(?:diingat|dicatat|ditekankan|digarisbawahi)\s+bahwa,?\s*/gi, replacement: "catatannya, " },
            { pattern: /\bdapat\s+(?:dikatakan|dipahami|dilihat)\s+bahwa,?\s*/gi, replacement: "" },
            { pattern: /\bpada\s+dasarnya,?\s*/gi, replacement: "intinya, " },
            { pattern: /\boleh\s+karena\s+itu,?\s+(?:sangat\s+)?(?:penting|krusial|esensial)\s+untuk\b/gi, replacement: "karena itu, langkah konkretnya yakni" },
            { pattern: /\boleh\s+karena\s+itu,?\s*/gi, replacement: "karena itu, " },
            { pattern: /\boleh\s+sebab\s+itu,?\s*/gi, replacement: "karena itu, " },
            { pattern: /\bdengan\s+demikian,?\s+(?:dapat\s+disimpulkan|dapat\s+dikatakan)\s+bahwa,?\s*/gi, replacement: "artinya, " },
            { pattern: /\bhal\s+(?:ini|tersebut)\s+(?:disebabkan|dikarenakan)\s+oleh,?\s*/gi, replacement: "hal ini terjadi lantaran " },
            { pattern: /\bhal\s+(?:ini|tersebut)\s+dikarenakan\b/gi, replacement: "faktor utamanya karena" },
            { pattern: /\bsehubungan\s+dengan\s+hal\s+tersebut,?\s*/gi, replacement: "menanggapi poin ini, " },
            { pattern: /\b(?:sebagai\s+kesimpulan|kesimpulannya|pada\s+akhirnya),?\s*/gi, replacement: "secara garis besar, " },
            { pattern: /\bsecara\s+keseluruhan,?\s*/gi, replacement: "secara umum, " },
            { pattern: /\bdapat\s+disimpulkan\s+bahwa,?\s*/gi, replacement: "bisa dipastikan bahwa " },

            // 4. Significance Inflation & Empty AI Vocabulary (R-16, R-36)
            { pattern: /\b(?:merupakan|menjadi)\s+(?:salah\s+satu\s+)?(?:aspek|faktor|hal|komponen|elemen)\s+yang\s+(?:sangat\s+)?(?:krusial|esensial|vital|penting)\b/gi, replacement: "sangat menentukan" },
            { pattern: /\bmerupakan\s+hal\s+yang\s+sangat\s+krusial\b/gi, replacement: "sangat penting" },
            { pattern: /\bsangat\s+krusial\b/gi, replacement: "sangat penting" },
            { pattern: /\bmerupakan\s+inovasi\s+teknologi\s+yang\s+sangat\s+krusial\b/gi, replacement: "menjadi inovasi teknologi yang berpengaruh besar" },
            { pattern: /\b(?:memegang|memainkan)\s+peran(?:an)?\s+(?:yang\s+)?(?:sangat\s+)?(?:penting|krusial|vital|utama|signifikan|besar)?\s*(?:dalam|pada|bagi)?\b/gi, replacement: "mengambil peran besar dalam " },
            { pattern: /\b(?:memegang|memainkan)\s+peran(?:an)?\b/gi, replacement: "berperan aktif" },
            { pattern: /\b(?:berfungsi|menjadi)\s+sebagai\s+bukti\s+nyata\s+(?:bahwa|dari)?\b/gi, replacement: "membuktikan" },
            { pattern: /\bsebuah\s+bukti\s+nyata\s+(?:bahwa|dari)?\b/gi, replacement: "bukti jelas bahwa" },
            { pattern: /\bmenyelami\s+(?:lebih\s+dalam|dunia|ranah|berbagai)?\s*/gi, replacement: "mempelajari " },
            { pattern: /\bmenyelami\b/gi, replacement: "mendalami" },
            { pattern: /\bpermadani\s+(?:inovasi|kehidupan|budaya|sosial|peradaban|teknologi|karya)?\b/gi, replacement: "ragam dinamika" },
            { pattern: /\bpermadani\b/gi, replacement: "keberagaman" },
            { pattern: /\bmercusuar\s+(?:harapan|transformasi|perubahan|kemajuan|inovasi|pendidikan)?\b/gi, replacement: "arah panduan" },
            { pattern: /\bmercusuar\b/gi, replacement: "pijakan utama" },
            { pattern: /\blanskap\s+(?:pendidikan|bisnis|teknologi|digital|ekonomi|keuangan|sosial|budaya|kontemporer)?\b/gi, replacement: "ranah" },
            { pattern: /\blanskap\b/gi, replacement: "bidang" },
            { pattern: /\beksplorasi\s+(?:lebih\s+dalam|lebih\s+jauh)?\b/gi, replacement: "mengkaji lebih jauh" },
            { pattern: /\bmerangkul\s+(?:perubahan\s+holistik|perubahan|transformasi)\b/gi, replacement: "menyesuaikan perubahan secara menyeluruh" },
            { pattern: /\bmerangkul\b/gi, replacement: "menerapkan" },
            { pattern: /\blandasan\s+masa\s+depan\b/gi, replacement: "pijakan ke depan" },
            { pattern: /\bsangat\s+penting\s+bagi\s+kita\s+untuk\b/gi, replacement: "kita perlu" },
            { pattern: /\bnamun\s+demikian,?\s*/gi, replacement: "namun di lapangan, " },
            { pattern: /\bdi\s+samping\s+itu,?\s*/gi, replacement: "selain itu, " },
            { pattern: /\bkomprehensif\s+dan\s+holistik\b/gi, replacement: "menyeluruh dan terarah" },
            { pattern: /\bmemberikan\s+kontribusi\s+(?:yang\s+)?(?:sangat\s+)?(?:signifikan|besar|nyata)\b/gi, replacement: "berkontribusi langsung" },
            { pattern: /\bmerangkul\s+perubahan\b/gi, replacement: "menyesuaikan diri dengan perubahan" },
            { pattern: /\bmembuka\s+potensi\s+(?:penuh|tanpa\s+batas)?\b/gi, replacement: "mengoptimalkan potensi" },
            { pattern: /\bmembuka\s+peluang\s+(?:emas|baru)?\b/gi, replacement: "membuka kesempatan baru" },
            { pattern: /\bharmoni\s+yang\s+indah\b/gi, replacement: "keselarasan yang baik" },
            { pattern: /\bmerajut\s+masa\s+depan\b/gi, replacement: "menyiapkan langkah ke depan" },
            { pattern: /\bmenatap\s+masa\s+depan\b/gi, replacement: "melihat ke depan" },
            { pattern: /\bmenjadi\s+landasan\s+utama\b/gi, replacement: "menjadi fondasi utama" },
            { pattern: /\bmemberikan\s+dampak\s+positif\b/gi, replacement: "membawa dampak baik" },
            { pattern: /\bmemberikan\s+dampak\s+negatif\b/gi, replacement: "menimbulkan dampak buruk" },
            { pattern: /\bberbagai\s+macam\b/gi, replacement: "beragam" },

            // 5. Negative Parallelism Elimination (R-36)
            { pattern: /\b(?:tidak|bukan)\s+hanya\s+([^\.,;]+?)\s*,\s*(?:tetapi|melainkan|namun)\s+juga\s+/gi, replacement: "selain $1, turut pula " },
            { pattern: /\b(?:tidak|bukan)\s+hanya\s+sekadar\s+([^\.,;]+?)\s*,\s*(?:tetapi|melainkan)\s+/gi, replacement: "selain $1, hal ini juga " },

            // 6. Idiomatic & Multi-Word Phrase Replacements (Natural Human Style)
            { pattern: /\btelah\s+mengubah\s+cara\s+kerja\b/gi, replacement: "kini merombak pola kerja" },
            { pattern: /\bcara\s+kerja\b/gi, replacement: "pola kerja" },
            { pattern: /\bmulai\s+mengadopsi\b/gi, replacement: "mulai beralih menerapkan" },
            { pattern: /\bteknologi\s+otomatisasi\b/gi, replacement: "sistem otomatisasi" },
            { pattern: /\bmeningkatkan\s+produktivitas\s+dan\s+efisiensi\s+operasional\b/gi, replacement: "menggenjot produktivitas sekaligus menekan biaya operasional" },
            { pattern: /\bmeningkatkan\s+produktivitas\s+dan\s+efisiensi\b/gi, replacement: "menggenjot produktivitas serta efisiensi" },
            { pattern: /\bdituntut\s+untuk\s+mempelajari\b/gi, replacement: "perlu memperbarui" },
            { pattern: /\bketerampilan\s+baru\b/gi, replacement: "keahlian baru" },
            { pattern: /\bagar\s+tetap\s+relevan\b/gi, replacement: "supaya tetap kompetitif" },
            { pattern: /\bpasar\s+tenaga\s+kerja\b/gi, replacement: "bursa kerja" },
            { pattern: /\bterus\s+berkembang\b/gi, replacement: "kian dinamis" },
            { pattern: /\btransformasi\s+digital\s+ini\b/gi, replacement: "arus digitalisasi ini" },
            { pattern: /\bmasa\s+depan\s+ekonomi\s+modern\b/gi, replacement: "arah ekonomi masa depan" },
            { pattern: /\bmetode\s+pembelajaran\s+daring\b/gi, replacement: "sistem pembelajaran daring" },
            { pattern: /\bdunia\s+pendidikan\s+tinggi\b/gi, replacement: "lingkup perguruan tinggi" },
            { pattern: /\bmengakses\s+materi\s+kuliah\b/gi, replacement: "mempelajari bahan kuliah" },
            { pattern: /\bdengan\s+lebih\s+fleksibel\b/gi, replacement: "secara lebih fleksibel" },
            { pattern: /\bkendala\s+jaringan\s+internet\b/gi, replacement: "hambatan koneksi internet" },
            { pattern: /\bsering\s+dihadapi\s+oleh\b/gi, replacement: "kerap dialami oleh" },
            { pattern: /\bpeserta\s+didik\b/gi, replacement: "mahasiswa" },
            { pattern: /\bmencari\s+solusi\s+efektif\b/gi, replacement: "merumuskan solusi konkret" },
            { pattern: /\bkesenjangan\s+fasilitas\b/gi, replacement: "ketimpangan fasilitas" },
            { pattern: /\bbelajar\s+teknologi\s+baru\b/gi, replacement: "mempelajari teknologi baru" },
            { pattern: /\bpada\s+dasarnya,?\s*kita\s+hanya\s+perlu\b/gi, replacement: "kuncinya ada pada kemauan untuk" },
            { pattern: /\bmeluangkan\s+waktu\s+secara\s+konsisten\b/gi, replacement: "menyisihkan waktu secara teratur" },
            { pattern: /\bsetiap\s+hari\b/gi, replacement: "setiap harinya" },

            // 7. Academic Case-Study Clichés (Clean, Human, Rigorous)
            { pattern: /\bBerdasarkan\s+(?:(?:studi|ilustrasi|analisis|uraian|penjelasan|paparan|data|kajian)\s+)?(?:kasus|soal|studi|permasalahan)?\s*(?:di atas|tersebut),?\s*/gi, replacement: "Mencermati paparan kasus di atas, " },
            { pattern: /\bsebagai seorang investor saya lebih memilih pendekatan\s*([a-zA-Z0-9_-]+)?\b/gi, replacement: "pilihan saya jatuh pada pendekatan $1" },
            { pattern: /\bsebagai seorang investor saya lebih memilih\b/gi, replacement: "saya lebih memilih" },
            { pattern: /\bsaya lebih memilih pendekatan\s*([a-zA-Z0-9_-]+)?\b/gi, replacement: "pilihan saya jatuh pada opsi $1" },
            { pattern: /\byaitu menggunakan model\b/gi, replacement: "yakni model" },
            { pattern: /\byaitu dengan menerapkan\b/gi, replacement: "dengan menerapkan" },
            { pattern: /\bAlasan utamanya adalah\s*(?:karena)?\s*/gi, replacement: "Alasannya sederhana: " },
            { pattern: /\bmemiliki asumsi dasar yang sangat ketat\b/gi, replacement: "memiliki asumsi yang terlampau kaku" },
            { pattern: /\basumsi dasar yang sangat ketat\b/gi, replacement: "asumsi yang terlampau kaku" },
            { pattern: /\byakni menganggap bahwa\b/gi, replacement: "karena menganggap bahwa" },
            { pattern: /\byakni mengasumsikan bahwa\b/gi, replacement: "karena bertumpu pada anggapan bahwa" },
            { pattern: /\bhanya dipengaruhi oleh satu faktor risiko sistematis tunggal\b/gi, replacement: "hanya bertumpu pada satu faktor risiko pasar" },
            { pattern: /\bhanya dipengaruhi oleh\b/gi, replacement: "hanya bertumpu pada" },
            { pattern: /\byaitu risiko pasar\s*\(yang diukur dengan Beta terhadap IHSG\)\b/gi, replacement: "yaitu risiko pasar (diukur lewat Beta terhadap IHSG)" },
            { pattern: /\byaitu risiko pasar\b/gi, replacement: "yaitu risiko pasar" },
            { pattern: /\bKetika\s+kondisi\s+pasar\s*(?:\(IHSG\))?\s*sedang\s+stagnan(?:\s+atau\s+tidak\s+berubah)?,?\s*(?:namun)?\s*/gi, replacement: "Padahal saat kondisi IHSG stagnan sekalipun, " },
            { pattern: /\b(?:beberapa\s+)?saham\s+tetap\s+menunjukkan\s+pergerakan\s+return\s+yang\s+fluktuatif\b/gi, replacement: "harga saham tetap berfluktuasi" },
            { pattern: /\btetap\s+menunjukkan\s+pergerakan\s+return\s+yang\s+fluktuatif\b/gi, replacement: "tetap berfluktuasi" },
            { pattern: /\bsehingga\s+(APT|__ANTISLOP_TOKEN_\d+__)\s+menjadi\s+jauh\s+lebih\s+relevan\b/gi, replacement: ". Keunggulan $1 justru tampak di sini" },
            { pattern: /\bhal ini membuktikan bahwa\b/gi, replacement: "ini bukti bahwa" },
            { pattern: /\bhal ini menunjukkan bahwa\b/gi, replacement: "ini menunjukkan bahwa" },
            { pattern: /\bada variabel lain di luar market return yang sedang beraksi\b/gi, replacement: "terdapat variabel lain di luar pasar yang turut bekerja" },
            { pattern: /\bvariabel lain di luar market return\b/gi, replacement: "faktor lain di luar pergerakan pasar" },
            { pattern: /\bsedang beraksi\b/gi, replacement: "turut berpengaruh" },
            { pattern: /\bDi sinilah\s+(APT|__ANTISLOP_TOKEN_\d+__)\s+menjadi\s+jauh\s+lebih\s+relevan\b/gi, replacement: "Keunggulan $1 justru tampak di sini" },
            { pattern: /\bKonsep\s+model\s+banyak\s+faktor\s*(?:(?:\(multi-factor model\)|\(__ANTISLOP_TOKEN_\d+__\)|__ANTISLOP_TOKEN_\d+__)\s*)?dalam\s+(APT|__ANTISLOP_TOKEN_\d+__)\s*tidak\s+mengikat\s+investor\s+pada\s+satu\s+faktor\s+saja\b/gi, replacement: "Model multi-faktor dalam $1 memberi ruang analisis yang jauh lebih fleksibel bagi investor" },
            { pattern: /\btidak mengikat investor pada satu faktor saja\b/gi, replacement: "tidak membatasi investor pada satu variabel semata" },

            // 8. Academic Discussion & IT Case-Study Phrases (Anti-GPTZero 4.10b)
            { pattern: /\bizin menyampaikan tanggapan atas pertanyaan diskusi terkait\b/gi, replacement: "perkenankan saya menyampaikan pandangan mengenai topik diskusi perihal" },
            { pattern: /\bizin menyampaikan tanggapan atas\b/gi, replacement: "perkenankan saya mengemukakan tanggapan mengenai" },
            { pattern: /\bpertanyaan diskusi terkait\b/gi, replacement: "topik diskusi seputar" },
            { pattern: /\bpertanyaan diskusi mengenai\b/gi, replacement: "fokus diskusi tentang" },
            { pattern: /\bstudi kasus perencanaan dan pengembangan sistem informasi\b/gi, replacement: "studi kasus perancangan serta implementasi sistem informasi" },
            { pattern: /\bperencanaan dan pengembangan sistem informasi\b/gi, replacement: "perancangan serta implementasi sistem informasi" },
            { pattern: /\bsistem informasi pada\b/gi, replacement: "sistem informasi di" },
            { pattern: /\bSesuai ketentuan, berikut adalah dua asumsi logis yang digunakan dalam analisis tanpa mengubah data utama kasus:\b/gi, replacement: "Berdasarkan kaidah analisis, terdapat dua premis rasional yang mendasari kajian ini tanpa mengubah esensi data kasus:" },
            { pattern: /\bberikut adalah dua asumsi logis yang digunakan dalam analisis tanpa mengubah data utama kasus\b/gi, replacement: "terdapat dua premis rasional yang mendasari kajian ini tanpa mengubah esensi data kasus" },
            { pattern: /\bberikut adalah dua asumsi logis\b/gi, replacement: "terdapat dua premis rasional" },
            { pattern: /\btanpa mengubah data utama kasus\b/gi, replacement: "tanpa merombak esensi data kasus" },
            { pattern: /\btelah memiliki komputer\/laptop kantor dan jaringan internet yang berfungsi stabil\b/gi, replacement: "sudah ditunjang fasilitas komputer kantor serta koneksi internet yang andal" },
            { pattern: /\btelah memiliki\b/gi, replacement: "kini telah ditunjang" },
            { pattern: /\bkomputer\/laptop kantor\b/gi, replacement: "fasilitas komputer kantor" },
            { pattern: /\bjaringan internet yang berfungsi stabil\b/gi, replacement: "koneksi internet yang stabil dan andal" },
            { pattern: /\bberfungsi stabil\b/gi, replacement: "beroperasi secara stabil dan optimal" },
            { pattern: /\bdapat difokuskan sepenuhnya untuk pengadaan jasa analisis, perancangan, pembuatan perangkat lunak, serta instalasi cloud hosting\/server lokal\b/gi, replacement: "dapat dialihkan secara maksimal guna pembiayaan jasa analisis, perancangan, pengembangan software, hingga sewa cloud server" },
            { pattern: /\bdapat difokuskan sepenuhnya untuk\b/gi, replacement: "dapat dialihkan seutuhnya guna" },
            { pattern: /\bdifokuskan sepenuhnya untuk\b/gi, replacement: "diarahkan secara maksimal demi" },
            { pattern: /\bpembuatan perangkat lunak\b/gi, replacement: "pengembangan software" },
            { pattern: /\bcloud hosting\/server lokal\b/gi, replacement: "layanan cloud server maupun server lokal" },
            { pattern: /\btanpa terbebani pembelian unit PC baru\b/gi, replacement: "tanpa perlu menguras anggaran untuk belanja komputer baru" },
            { pattern: /\btanpa terbebani pembelian unit\b/gi, replacement: "tanpa terbebani belanja unit" },
            { pattern: /\bpembelian unit PC baru\b/gi, replacement: "belanja unit komputer anyar" },
            { pattern: /\bunit PC baru\b/gi, replacement: "komputer anyar" },
            { pattern: /\bPemilik dan kedua staf administrasi terbiasa mengoperasikan komputer dasar, aplikasi perkantoran, dan ponsel pintar\b/gi, replacement: "Pihak pemilik bersama kedua staf administrasi telah terbiasa memakai komputer, software kantor, maupun smartphone" },
            { pattern: /\bterbiasa mengoperasikan\b/gi, replacement: "sudah familier menggunakan" },
            { pattern: /\bkomputer dasar\b/gi, replacement: "perangkat komputer" },
            { pattern: /\baplikasi perkantoran\b/gi, replacement: "software perkantoran" },
            { pattern: /\bponsel pintar\b/gi, replacement: "smartphone" },
            { pattern: /\bkurva pembelajaran\b/gi, replacement: "proses adaptasi dan pembelajaran" },
            { pattern: /\brelatif singkat dan tidak memerlukan biaya pelatihan khusus yang mahal\b/gi, replacement: "akan berjalan relatif cepat tanpa perlu mengalokasikan biaya pelatihan khusus" },
            { pattern: /\brelatif singkat\b/gi, replacement: "relatif cepat" },
            { pattern: /\btidak memerlukan biaya pelatihan khusus yang mahal\b/gi, replacement: "tanpa perlu mengalokasikan biaya pelatihan khusus" },
            { pattern: /\bbiaya pelatihan khusus yang mahal\b/gi, replacement: "biaya pelatihan khusus yang besar" },
            { pattern: /\blangkah perencanaan sistem informasi mencakup beberapa tahapan krusial\b/gi, replacement: "tahapan perancangan sistem informasi menitikberatkan pada sejumlah fase kunci" },
            { pattern: /\bmencakup beberapa tahapan krusial\b/gi, replacement: "menitikberatkan pada sejumlah tahapan esensial" },
            { pattern: /\bbeberapa tahapan krusial\b/gi, replacement: "sejumlah fase kunci" },
            { pattern: /\btahapan krusial\b/gi, replacement: "tahapan esensial" },

            // 9. Multi-Detector Academic Clichés (Turnitin & Drillbit Anti-Plagiarism Targets)
            { pattern: /\badalah\s+merupakan\s+(?:salah\s+satu\s+)?/gi, replacement: "menjadi salah satu " },
            { pattern: /\bsangat\s+penting\s+untuk\s+diperhatikan\s+bahwa,?\s*/gi, replacement: "poin kuncinya yakni " },
            { pattern: /\bsebagaimana\s+(?:telah\s+)?dijelaskan\s+(?:sebelumnya|di\s+atas),?\s*/gi, replacement: "seperti yang diulas sebelumnya, " },
            { pattern: /\bdalam\s+rangka\s+mencapai\s+tujuan\s+tersebut,?\s*/gi, replacement: "guna meraih target tersebut, " },
            { pattern: /\bmemiliki\s+peranan\s+yang\s+sangat\s+penting\s+dalam\b/gi, replacement: "berpengaruh besar terhadap" },
            { pattern: /\bdapat\s+ditarik\s+kesimpulan\s+bahwa,?\s*/gi, replacement: "garis besarnya, " },
            { pattern: /\bhal\s+ini\s+sejalan\s+dengan\s+(?:penelitian|kajian|studi)\s+yang\s+dilakukan\s+oleh\b/gi, replacement: "temuan ini selaras dengan studi" },
            { pattern: /\bberdasarkan\s+hasil\s+analisis\s+data\s*(?:di\s+atas|tersebut)?,?\s*/gi, replacement: "menilik hasil telaah data di atas, " },
            { pattern: /\btidak\s+dapat\s+dielakkan\s+bahwa,?\s*/gi, replacement: "jelas terlihat bahwa " },
            { pattern: /\btujuan\s+utama\s+dari\s+(?:penulisan|penelitian|kajian)\s+ini\s+adalah\s+(?:untuk)?\b/gi, replacement: "fokus utama kajian ini diarahkan untuk" },
            { pattern: /\bmerupakan\s+sebuah\s+keniscayaan\s+bahwa,?\s*/gi, replacement: "wajar bila " },
            { pattern: /\bmenjadi\s+sorotan\s+utama\s+dalam\b/gi, replacement: "menjadi perhatian utama di" },
            { pattern: /\bdalam\s+konteks\s+ini,?\s*(?:dapat\s+dipahami\s+bahwa)?\s*/gi, replacement: "dalam hal ini, " },
            { pattern: /\bmemberikan\s+implikasi\s+yang\s+signifikan\s+terhadap\b/gi, replacement: "berdampak langsung pada" },
            { pattern: /\bmenghadapi\s+berbagai\s+macam\s+tantangan\s+(?:yang\s+)?kompleks\b/gi, replacement: "menghadapi tantangan berlapis" },
            { pattern: /\bdalam\s+upaya\s+(?:untuk\s+)?meningkatkan\b/gi, replacement: "guna mendorong kenaikan" },
            { pattern: /\bhal\s+tersebut\s+menunjukkan\s+adanya\b/gi, replacement: "kondisi ini memperlihatkan adanya" },
            { pattern: /\bmenjadi\s+tolok\s+ukur\s+keberhasilan\b/gi, replacement: "menjadi barometer capaian" },
            { pattern: /\bmemiliki\s+korelasi\s+positif\s+dengan\b/gi, replacement: "berbanding lurus dengan" },

            // 10. September 2026 Multi-Detector Clichés (Turnitin 2026, Drillbit, GPTZero 4.10b, Copyleaks, ZeroGPT, QuillBot)
            { pattern: /\bdalam\s+era\s+transformasi\s+digital(?:\s+yang\s+serba\s+cepat)?\b/gi, replacement: "pada era digitalisasi saat ini" },
            { pattern: /\bperlu\s+digarisbawahi\s+bahwa,?\s*/gi, replacement: "catatannya, " },
            { pattern: /\bpada\s+hakikatnya,?\s*/gi, replacement: "sejatinya, " },
            { pattern: /\btidak\s+dapat\s+disangkal\s+bahwa,?\s*/gi, replacement: "terlihat jelas bahwa " },
            { pattern: /\bmemiliki\s+peran\s+yang\s+tak\s+terelakkan\s+dalam\b/gi, replacement: "mengambil peran sentral dalam" },
            { pattern: /\bmerupakan\s+instrumen\s+fundamental(?:\s+yang\s+senantiasa)?\b/gi, replacement: "menjadi sarana utama yang" },
            { pattern: /\bmencerminkan\s+komitmen\s+mendalam(?:\s+untuk)?\b/gi, replacement: "menunjukkan keseriusan dalam" },
            { pattern: /\bdalam\s+lanskap\s+teknologi\s+saat\s+ini\b/gi, replacement: "pada pemanfaatan teknologi saat ini" },
            { pattern: /\bsecara\s+garis\s+besar\s+dapat\s+disimpulkan\s+bahwa,?\s*/gi, replacement: "intinya, " },
            { pattern: /\bpatut\s+dicatat\s+bahwa,?\s*/gi, replacement: "perlu dicermati bahwa " },
            { pattern: /\bmemegang\s+peranan\s+krusial\b/gi, replacement: "berperan sangat penting" },
            { pattern: /\bmemberikan\s+kontribusi\s+yang\s+signifikan\b/gi, replacement: "berkontribusi nyata" },
            { pattern: /\bmenjadi\s+bukti\s+nyata\s+dari\b/gi, replacement: "membuktikan secara langsung" },
            { pattern: /\bmerupakan\s+salah\s+satu\s+aspek\s+kunci\b/gi, replacement: "menjadi aspek penting" },
            { pattern: /\bpada\s+dasarnya\s+dapat\s+dipahami\s+bahwa\b/gi, replacement: "wajar dipahami bahwa" },
            { pattern: /\bdalam\s+konteks\s+ini\s+dapat\s+dikatakan\s+bahwa\b/gi, replacement: "dalam hal ini, " },
            { pattern: /\blangkah\s+strategis\s+yang\s+harus\s+diambil\s+adalah\b/gi, replacement: "langkah konkretnya yakni" },

            // 11. Anti-slop: 2026 fresh detector targets (Turnitin, GPTZero, Copyleaks, ZeroGPT, Drillbit)
            // Significance Inflation & Abstract AI Vocabulary (antislop-copywriting §Significance Inflation)
            { pattern: /\bberkelanjutan\s+dan\s+komprehensif\b/gi, replacement: "menyeluruh dan konsisten" },
            { pattern: /\bsecara\s+holistik\s+dan\s+berkelanjutan\b/gi, replacement: "secara menyeluruh dan terencana" },
            { pattern: /\bsinergi\s+(?:yang\s+(?:kuat|harmonis|optimal))?\b/gi, replacement: "koordinasi yang erat" },
            { pattern: /\bsinergitas\b/gi, replacement: "keselarasan kerja" },
            { pattern: /\brobust\b/gi, replacement: "andal" },
            { pattern: /\bproaktif\s+dalam\s+menghadapi\b/gi, replacement: "siap menghadapi" },
            { pattern: /\bsecara\s+proaktif\b/gi, replacement: "dengan inisiatif" },
            { pattern: /\bparadigma\s+(?:baru|modern|berpikir)?\b/gi, replacement: "cara pandang" },
            { pattern: /\bpola\s+pikir\s+yang\s+inovatif\b/gi, replacement: "cara berpikir yang segar" },
            { pattern: /\bkomprehensif\s+dan\s+mendalam\b/gi, replacement: "menyeluruh dan rinci" },
            { pattern: /\bkomprehensif\b/gi, replacement: "menyeluruh" },

            // Filler Parallelism & Empty Connectors (antislop-copywriting §Rule of Three Overuse)
            { pattern: /\bselain\s+itu,?\s+(?:juga\s+)?perlu\s+diperhatikan\s+bahwa,?\s*/gi, replacement: "hal lain yang perlu dicermati, " },
            { pattern: /\bdi\s+sisi\s+lain,?\s+(?:juga\s+)?perlu\s+diingat\s+bahwa,?\s*/gi, replacement: "sebaliknya, " },
            { pattern: /\bdalam\s+hal\s+ini,?\s+(?:juga\s+)?(?:harus|perlu)\s+diperhatikan\s+bahwa,?\s*/gi, replacement: "catatannya, " },
            { pattern: /\byang\s+mana\s+(?:hal\s+ini\s+)?menunjukkan\b/gi, replacement: "yang menunjukkan" },
            { pattern: /\byang\s+mana\s+(?:hal\s+ini\s+)?membuktikan\b/gi, replacement: "yang membuktikan" },
            { pattern: /\byang\s+mana\s+/gi, replacement: "yang " },

            // Actorless Passive & Inanimate Subject with Human Verb (antislop-copywriting §Actorless Passive)
            { pattern: /\bhal\s+ini\s+(?:mengajarkan|memberitahu|mengingatkan)\s+kita\s+bahwa\b/gi, replacement: "dari sini kita tahu bahwa" },
            { pattern: /\bkita\s+(?:perlu|harus)\s+memahami\s+bahwa\b/gi, replacement: "penting untuk dipahami bahwa" },
            { pattern: /\bkita\s+(?:perlu|harus)\s+mengakui\s+bahwa\b/gi, replacement: "perlu diakui bahwa" },
            { pattern: /\bdalam\s+perjalanannya,?\s*/gi, replacement: "seiring berjalannya waktu, " },

            // Empty Positive Conclusions (antislop-copywriting §Generic Positive Conclusion)
            { pattern: /\bmasa\s+depan\s+(?:yang\s+)?(?:lebih\s+)?cerah\b/gi, replacement: "prospek yang lebih baik" },
            { pattern: /\bmenuju\s+masa\s+depan\s+yang\s+lebih\s+(?:baik|cerah|gemilang)\b/gi, replacement: "ke arah yang lebih baik" },
            { pattern: /\bjalan\s+menuju\s+(?:kesuksesan|kejayaan|kemajuan)\b/gi, replacement: "langkah ke depan" },
            { pattern: /\btanpa\s+ragu\b/gi, replacement: "dengan keyakinan" },

            // Staccato Drama (antislop-copywriting §Staccato Drama)
            { pattern: /\btanpa\s+ada\s+pengecualian\b/gi, replacement: "secara menyeluruh" },
            { pattern: /\bdari\s+hati\s+ke\s+hati\b/gi, replacement: "secara terbuka" }
        ],

        // Comprehensive Per-Tone Lexical and Rhetorical Replacements (7 Styles)
        toneReplacements: {
            academic: [
                { pattern: /\b(?:izin\s+)?(?:menyampaikan\s+tanggapan|menanggapi)\s+atas\b/gi, replacement: "perkenankan saya menyampaikan telaah kritis mengenai" },
                { pattern: /\b(?:izin\s+)?(?:menyampaikan\s+tanggapan|menanggapi)\b/gi, replacement: "perkenankan saya mengemukakan telaah akademik" },
                { pattern: /\bsangat\s+bagus\b/gi, replacement: "berkualitas tinggi" },
                { pattern: /\bmenguntungkan\b/gi, replacement: "memberikan nilai tambah nyata" },
                { pattern: /\bbikin\b/gi, replacement: "menghasilkan" },
                { pattern: /\bnggak\b/gi, replacement: "tidak" },
                { pattern: /\bcuma\b/gi, replacement: "hanya" },
                { pattern: /\bbanget\b/gi, replacement: "sangat" },
                { pattern: /\bintinya\b/gi, replacement: "secara substansial" },
                { pattern: /\bjelas\s+banget\b/gi, replacement: "tampak secara eksplisit" },
                { pattern: /\bmasalah\s+besar\b/gi, replacement: "hambatan fundamental" },
                { pattern: /\bcara\s+ini\b/gi, replacement: "metodologi ini" },
                { pattern: /\bhasilnya\s+bagus\b/gi, replacement: "luarannya terbukti optimal" },
                { pattern: /\bmenurut\s+saya\b/gi, replacement: "berdasarkan telaah kritis," }
            ],
            tuton: [
                { pattern: /\bizin\s+menyampaikan\s+tanggapan\s+atas\s+pertanyaan\s+diskusi\s+(?:sesi\s+\d+\s+)?terkait\b/gi, replacement: "Izin menanggapi diskusi perihal" },
                { pattern: /\bizin\s+menyampaikan\s+tanggapan\s+atas\s+pertanyaan\s+diskusi\b/gi, replacement: "Izin menyampaikan tanggapan mengenai" },
                { pattern: /\bizin\s+menyampaikan\s+tanggapan\s+atas\b/gi, replacement: "Izin memberikan pandangan terkait" },
                { pattern: /\bpertanyaan\s+diskusi\s+terkait\b/gi, replacement: "topik diskusi perihal" },
                { pattern: /\bpertanyaan\s+diskusi\s+mengenai\b/gi, replacement: "fokus diskusi tentang" },
                { pattern: /\bberdasarkan\s+(?:studi\s+)?kasus\s*(?:di\s+atas|tersebut)?,?\s*(?:dapat\s+dianalisis\s+bahwa)?/gi, replacement: "mencermati paparan kasus di atas, menurut saya " },
                { pattern: /\bsesuai\s+dengan\s+materi\s+inisiasi\b/gi, replacement: "mengacu pada materi inisiasi dan BMP," },
                { pattern: /\bsebagaimana\s+(?:telah\s+)?dijelaskan\s+dalam\s+modul\b/gi, replacement: "seperti yang diuraikan pada modul pokok," },
                { pattern: /\bdapat\s+ditarik\s+kesimpulan\s+bahwa,?\s*/gi, replacement: "poin penting yang bisa kita petik yakni " },
                { pattern: /\bsebagai\s+seorang\s+mahasiswa\s*(?:saya\s+memandang\s+bahwa)?/gi, replacement: "menurut pemahaman saya," },
                { pattern: /\bdalam\s+hal\s+ini\s+penulis\s+berpendapat\s+bahwa\b/gi, replacement: "dari sudut pandang saya," },
                { pattern: /\boleh\s+karena\s+itu\s+sangat\s+disarankan\s+untuk\b/gi, replacement: "karena itu, langkah realistisnya adalah" },
                { pattern: /\bmerupakan\s+hal\s+yang\s+sangat\s+penting\b/gi, replacement: "menjadi hal yang sangat krusial" },
                { pattern: /\bmemberikan\s+kontribusi\s+signifikan\b/gi, replacement: "membawa dampak positif nyata" },
                { pattern: /\bmemiliki\s+pengaruh\s+yang\s+sangat\s+besar\b/gi, replacement: "sangat menentukan capaian hasil" },
                { pattern: /\bhal\s+tersebut\s+disebabkan\s+oleh\s+karena\b/gi, replacement: "faktor pendorong utamanya yaitu" },
                { pattern: /\bperlu\s+ditekankan\s+bahwa\b/gi, replacement: "catatan pentingnya yakni" },
                { pattern: /\bsebagai\s+kesimpulan,?\s*/gi, replacement: "secara ringkas," },
                { pattern: /\bdemikian\s+tanggapan\s+yang\s+dapat\s+saya\s+sampaikan,?\s*/gi, replacement: "Demikian tanggapan dari saya, " },
                { pattern: /\bmohon\s+arahan\s+dan\s+bimbingannya\b/gi, replacement: "mohon masukan dan tanggapannya" }
            ],
            formal: [
                { pattern: /\b(?:izin\s+)?(?:menyampaikan\s+tanggapan|menanggapi)\s+atas\b/gi, replacement: "perkenankan kami menyampaikan tanggapan resmi mengenai" },
                { pattern: /\b(?:izin\s+)?(?:menyampaikan\s+tanggapan|menanggapi)\b/gi, replacement: "perkenankan kami menyampaikan tanggapan" },
                { pattern: /\bkita\s+harus\b/gi, replacement: "manajemen perlu" },
                { pattern: /\bkami\s+bermaksud\s+untuk\b/gi, replacement: "kami berencana" },
                { pattern: /\bdiharapkan\s+dapat\s+memberikan\b/gi, replacement: "ditargetkan menghasilkan" },
                { pattern: /\bngomong-ngomong\b/gi, replacement: "sebagai catatan tambahan" },
                { pattern: /\bmelakukan\s+koordinasi\s+lebih\s+lanjut\b/gi, replacement: "berkoordinasi kembali" },
                { pattern: /\bmengambil\s+langkah\s+strategis\b/gi, replacement: "menjalankan langkah konkret" },
                { pattern: /\bmeningkatkan\s+nilai\s+tambah\b/gi, replacement: "memperkuat daya saing" },
                { pattern: /\bsehubungan\s+dengan\s+hal\s+tersebut\b/gi, replacement: "menindaklanjuti poin tersebut" },
                { pattern: /\bmemaksimalkan\s+efisiensi\s+operasional\b/gi, replacement: "mengoptimalkan efisiensi operasional" },
                { pattern: /\bmemaksimalkan\s+efisiensi\b/gi, replacement: "mengoptimalkan efisiensi" },
                { pattern: /\bguna\s+mencapai\s+target\s+yang\s+telah\s+ditetapkan\b/gi, replacement: "demi memenuhi target kerja" },
                { pattern: /\bmasalah\s+internal\b/gi, replacement: "kendala operasional internal" },
                { pattern: /\bperlu\s+segera\s+ditangani\b/gi, replacement: "menjadi prioritas penyelesaian" }
            ],
            casual: [
                { pattern: /\b(?:izin\s+)?(?:menyampaikan\s+tanggapan|menanggapi)\s+atas\b/gi, replacement: "aku mau share pandangan seputar" },
                { pattern: /\b(?:izin\s+)?(?:menyampaikan\s+tanggapan|menanggapi)\b/gi, replacement: "aku mau berpendapat" },
                { pattern: /\bnamun\s+demikian,?\b/gi, replacement: "tapi nyatanya," },
                { pattern: /\boleh\s+karena\s+itu,?\b/gi, replacement: "makanya," },
                { pattern: /\bdiperlukan\b/gi, replacement: "butuh" },
                { pattern: /\bsebenarnya\b/gi, replacement: "sebetulnya" },
                { pattern: /\bmenurut\s+pendapat\s+saya\b/gi, replacement: "kalau menurut saya pribadi" },
                { pattern: /\btidak\s+dapat\s+dipungkiri\b/gi, replacement: "jujur saja" },
                { pattern: /\bsangat\s+menyenangkan\b/gi, replacement: "seru banget" },
                { pattern: /\bmembutuhkan\s+waktu\b/gi, replacement: "butuh waktu" },
                { pattern: /\bmerupakan\s+hal\s+yang\s+wajar\b/gi, replacement: "wajar banget" },
                { pattern: /\bhal\s+ini\s+membuktikan\s+bahwa\b/gi, replacement: "ini bukti kalau" },
                { pattern: /\btetapi\s+pada\s+akhirnya\b/gi, replacement: "tapi ujung-ujungnya" },
                { pattern: /\bperlu\s+diingat\s+bahwa\b/gi, replacement: "ingat ya," },
                { pattern: /\bhanya\s+sekadar\b/gi, replacement: "cuma" }
            ],
            journalistic: [
                { pattern: /\bdapat\s+dikatakan\s+bahwa\b/gi, replacement: "catatannya," },
                { pattern: /\bmenurut\s+hemat\s+saya\b/gi, replacement: "pantauan di lapangan," },
                { pattern: /\bhal\s+ini\s+sangat\s+menarik\b/gi, replacement: "kondisi ini memantik perhatian" },
                { pattern: /\bberdasarkan\s+informasi\s+yang\s+dihimpun,?\s*(?:dapat\s+dilaporkan\s+bahwa)?\s*/gi, replacement: "informasi yang dihimpun di lapangan mencatat bahwa " },
                { pattern: /\bdapat\s+dilaporkan\s+bahwa,?\s*/gi, replacement: "laporan di lapangan menunjukkan bahwa " },
                { pattern: /\bhal\s+ini\s+memicu\s+kekhawatiran\b/gi, replacement: "situasi ini menuai sorotan" },
                { pattern: /\bmenjadi\s+perbincangan\s+hangat\b/gi, replacement: "ramai disorot publik" },
                { pattern: /\bmemberikan\s+tanggapan\s+resmi\b/gi, replacement: "angkat bicara" },
                { pattern: /\bhingga\s+berita\s+ini\s+diturunkan\b/gi, replacement: "sampai saat ini," },
                { pattern: /\bmengalami\s+lonjakan\s+signifikan\b/gi, replacement: "melonjak tajam" },
                { pattern: /\bpihak\s+terkait\b/gi, replacement: "otoritas berwenang" }
            ],
            creative: [
                { pattern: /\bpada\s+akhirnya\b/gi, replacement: "lambat laun" },
                { pattern: /\bsecara\s+nyata\b/gi, replacement: "terasa begitu hidup" },
                { pattern: /\bseiring\s+berjalannya\s+waktu,?\s*/gi, replacement: "perlahan tapi pasti, " },
                { pattern: /\bmenyimpan\s+sejuta\s+makna\b/gi, replacement: "menyimpan arti mendalam" },
                { pattern: /\bsebuah\s+perjalanan\s+panjang\b/gi, replacement: "langkah demi langkah" },
                { pattern: /\bmelukiskan\s+keindahan\b/gi, replacement: "menghadirkan potret nyata" },
                { pattern: /\bterpatri\s+dalam\s+sanubari\b/gi, replacement: "selalu teringat jelas" },
                { pattern: /\btak\s+lekang\s+oleh\s+waktu\b/gi, replacement: "tetap bertahan melintasi masa" },
                { pattern: /\bmenembus\s+ruang\s+dan\s+waktu\b/gi, replacement: "melampaui batasan masa" }
            ],
            simple: [
                { pattern: /\b(?:dapat\s+dikatakan\s+bahwa|pada\s+dasarnya|dalam\s+hal\s+ini)\b/gi, replacement: "" },
                { pattern: /\bdalam\s+rangka\s+untuk\b/gi, replacement: "untuk" },
                { pattern: /\bpada\s+saat\s+sekarang\s+ini\b/gi, replacement: "kini" },
                { pattern: /\bmempunyai\s+kemampuan\s+untuk\b/gi, replacement: "bisa" },
                { pattern: /\bmelakukan\s+tindakan\s+perbaikan\b/gi, replacement: "memperbaiki" },
                { pattern: /\bmemberikan\s+bantuan\s+kepada\b/gi, replacement: "membantu" },
                { pattern: /\bmengakibatkan\s+terjadinya\s+penurunan\b/gi, replacement: "menurunkan" },
                { pattern: /\bdengan\s+cara\s+melakukan\b/gi, replacement: "dengan" },
                { pattern: /\bmelakukan\s+peninjauan\s+kembali\b/gi, replacement: "meninjau ulang" },
                { pattern: /\bmemerlukan\s+alokasi\s+waktu\b/gi, replacement: "memakan waktu" }
            ]
        },

        // Natural Human Transitions for Sentence Pacing (No inflated academic buzzwords)
        transitions: {
            academic: [
                "Dalam praktiknya,",
                "Di sisi lain,",
                "Perlu dicermati,",
                "Terkait hal itu,",
                "Menariknya,",
                "Catatan pentingnya,"
            ],
            tuton: [
                "Menurut pemahaman saya,",
                "Mengacu pada modul BMP,",
                "Terkait hal tersebut,",
                "Menariknya pada kasus ini,",
                "Dalam praktiknya di lapangan,",
                "Catatan pentingnya,"
            ],
            formal: [
                "Terkait hal tersebut,",
                "Dalam pelaksanaannya,",
                "Lebih lanjut,",
                "Sejalan dengan hal itu,"
            ],
            casual: [
                "Sebetulnya,",
                "Menariknya,",
                "Bisa dibilang,",
                "Nyatanya,"
            ],
            journalistic: [
                "Di sisi lain,",
                "Kenyataannya,",
                "Sementara itu,"
            ],
            creative: [
                "Menariknya,",
                "Tanpa disadari,",
                "Satu hal yang pasti,"
            ],
            simple: [
                "Artinya,",
                "Selain itu,",
                "Intinya,"
            ]
        },

        // Tone-Specific Greetings & Openings (Non-Islamic Greetings Harmonization)
        openings: {
            academic: "Salam sejahtera bagi rekan-rekan civitas akademika,",
            tuton: "Selamat pagi Tutor dan rekan-rekan mahasiswa sekalian,",
            formal: "Yth. Bapak/Ibu dan rekan-rekan sekalian,",
            casual: "Halo teman-teman,",
            journalistic: "Salam redaksi,",
            creative: "Salam hangat untuk kita semua,",
            simple: "Halo,"
        },

        // Tone-Specific Closings & Sign-Offs (Non-Islamic Closings Harmonization)
        closings: {
            academic: "Demikian kajian kritis yang dapat penulis sampaikan, semoga memberikan kontribusi konstruktif terhadap pengembangan wacana keilmuan. Terima kasih.",
            tuton: "Demikian tanggapan dari saya, mohon masukan dan koreksi dari Tutor serta rekan-rekan mahasiswa sekalian. Terima kasih.",
            formal: "Demikian yang dapat kami sampaikan. Atas perhatian, arahan, dan kerja sama Bapak/Ibu, kami ucapkan terima kasih.",
            casual: "Sekian dulu dari aku ya, semoga bermanfaat buat teman-teman! Gimana menurut kalian? Yuk diskusi!",
            journalistic: "Demikian rangkuman informasi terkini dari lapangan yang dapat dihimpun redaksi.",
            creative: "Demikian sekelumit refleksi, semoga mengendap menjadi wawasan yang bermakna bagi perjalanan kita.",
            simple: "Sekian dan terima kasih."
        },

        samplePrompts: {
            tuton: `Selamat pagi Tutor dan rekan-rekan mahasiswa sekalian,

Izin menyampaikan tanggapan atas pertanyaan diskusi sesi ini terkait perencanaan sistem informasi pada CV Rasa Mandiri.

Berdasarkan modul BMP dan paparan studi kasus, berikut adalah dua asumsi rasional yang digunakan dalam analisis tanpa merubah esensi data utama kasus:
1. CV Rasa Mandiri telah memiliki komputer kantor dan jaringan internet yang berfungsi stabil. Dengan asumsi ini, anggaran Rp75.000.000 dapat dialihkan secara maksimal guna pembiayaan jasa perancangan sistem dan sewa cloud server tanpa terbebani pembelian unit PC baru.
2. Pemilik serta staf administrasi sudah terbiasa mengoperasikan komputer dasar dan ponsel pintar. Asumsi ini membuat alur adaptasi dan pembelajaran berjalan relatif cepat tanpa memerlukan biaya pelatihan khusus yang mahal.

Demikian tanggapan yang dapat saya sampaikan, mohon masukan dan koreksi dari Tutor serta rekan-rekan mahasiswa sekalian. Terima kasih.`,
            academic: "Kecerdasan buatan (AI) merupakan inovasi teknologi yang sangat krusial dalam era modern ini. Tidak dapat dipungkiri bahwa AI memainkan peran penting dalam mentransformasi sektor pendidikan dan riset akademik. Sebagai kesimpulan, pemanfaatan AI yang komprehensif dan holistik akan menjadi landasan utama bagi kemajuan peradaban masa depan.",
            formal: "Sehubungan dengan perkembangan implementasi sistem informasi, perlu diingat bahwa koordinasi antar divisi memegang peranan penting dalam pencapaian target. Oleh karena itu, sangat penting untuk meningkatkan efisiensi kerja demi memberikan kontribusi signifikan bagi perusahaan.",
            casual: "Belajar hal baru di era digital saat ini memang sangat menyenangkan. Tidak dapat dipungkiri bahwa banyak sekali aplikasi yang bisa membantu kita belajar lebih cepat. Sebagai kesimpulan, jangan ragu untuk menyelami lebih dalam berbagai ilmu yang kamu minati."
        }
    },

    en: {
        name: "English",
        flag: "🇬🇧",
        
        cliches: [
            // 1. Em Dash Elimination (R-02)
            { pattern: /\s*—\s*/g, replacement: ", " },
            { pattern: /\s*--\s*/g, replacement: ", " },

            // 2. Empty AI Vocabulary & Significance Inflation (R-16, R-36)
            { pattern: /\bdelve\s+into\b/gi, replacement: "explore" },
            { pattern: /\bdelving\s+into\b/gi, replacement: "examining" },
            { pattern: /\ba\s+testament\s+to\b/gi, replacement: "clear proof of" },
            { pattern: /\bplays\s+a\s+(?:pivotal|crucial|vital|key)\s+role\s+in\b/gi, replacement: "is central to" },
            { pattern: /\bplays\s+an\s+essential\s+role\s+in\b/gi, replacement: "directly influences" },
            { pattern: /\bin\s+today's\s+(?:digital\s+age|fast-paced\s+world|interconnected\s+society)\b/gi, replacement: "nowadays" },
            { pattern: /\bin\s+the\s+modern\s+era\b/gi, replacement: "today" },
            { pattern: /\b(?:rich\s+)?tapestry\s+(?:of|that)?\b/gi, replacement: "wide array of" },
            { pattern: /\btapestry\b/gi, replacement: "diversity" },
            { pattern: /\bseamlessly\s+integrated?\b/gi, replacement: "smoothly linked" },
            { pattern: /\bfoster\s+a\s+sense\s+of\b/gi, replacement: "encourage" },
            { pattern: /\bbeacon\s+(?:of\s+hope|of\s+transformation|of\s+light|of\s+change)?\b/gi, replacement: "promising guide" },
            { pattern: /\bbeacon\b/gi, replacement: "clear benchmark" },
            { pattern: /\blandscape\s+(?:of|in)?\b/gi, replacement: "realm of" },
            { pattern: /\blandscape\b/gi, replacement: "sector" },
            { pattern: /\bparamount\s+importance\b/gi, replacement: "key priority" },
            { pattern: /\bcomprehensive\s+overview\b/gi, replacement: "clear summary" },
            { pattern: /\bholistic\s+approach\b/gi, replacement: "integrated method" },
            { pattern: /\bunlock(?:ing)?\s+the\s+potential\b/gi, replacement: "maximizing ability" },
            { pattern: /\bgame-changer\b/gi, replacement: "significant shift" },

            // 3. Filler Phrases
            { pattern: /\bit\s+is\s+(?:important|worth)\s+noting\s+that,?\s*/gi, replacement: "notably, " },
            { pattern: /\bit\s+is\s+undeniable\s+that,?\s*/gi, replacement: "clearly, " },
            { pattern: /\bin\s+order\s+to\b/gi, replacement: "to" },
            { pattern: /\bdue\s+to\s+the\s+fact\s+that\b/gi, replacement: "because" },
            { pattern: /\bfurthermore,?\s*/gi, replacement: "moreover, " },
            { pattern: /\bin\s+conclusion,?\s*/gi, replacement: "ultimately, " },
            { pattern: /\ball\s+in\s+all,?\s*/gi, replacement: "on the whole, " },

            // 4. Negative Parallelism (R-36)
            { pattern: /\bnot\s+only\s+([^\.,;]+?)\s*,\s*but\s+also\s+/gi, replacement: "along with $1, it also " },

            // 5. Multi-Detector Academic & Professional AI Clichés (Turnitin & GPTZero Targets)
            { pattern: /\bin\s+today's\s+world\b/gi, replacement: "today" },
            { pattern: /\bit\s+is\s+essential\s+to\s+note\s+that,?\s*/gi, replacement: "notably, " },
            { pattern: /\bserves\s+as\s+a\s+reminder\s+that\b/gi, replacement: "shows that" },
            { pattern: /\bpaves\s+the\s+way\s+for\b/gi, replacement: "enables" },
            { pattern: /\bhas\s+revolutionized\s+the\s+way\b/gi, replacement: "fundamentally changed how" },
            { pattern: /\ba\s+wide\s+variety\s+of\b/gi, replacement: "various" },
            { pattern: /\bsheds\s+light\s+on\b/gi, replacement: "clarifies" },
            { pattern: /\bplays\s+a\s+significant\s+role\s+in\b/gi, replacement: "is influential in" },
            { pattern: /\ba\s+multitude\s+of\b/gi, replacement: "many" },
            { pattern: /\bfurther\s+analysis\s+reveals\s+that\b/gi, replacement: "closer inspection shows that" },
            { pattern: /\bwith\s+the\s+advent\s+of\b/gi, replacement: "with the rise of" },
            { pattern: /\bat\s+the\s+forefront\s+of\b/gi, replacement: "leading" },
            { pattern: /\bserves\s+as\s+a\s+cornerstone\s+for\b/gi, replacement: "provides a solid foundation for" },
            { pattern: /\bit\s+is\s+worth\s+emphasizing\s+that\b/gi, replacement: "crucially," },

            // 6. September 2026 Multi-Detector Clichés (Turnitin, Copyleaks, GPTZero 4.10b, QuillBot)
            { pattern: /\bin\s+today's\s+rapidly\s+evolving(?:\s+digital)?\s+landscape\b/gi, replacement: "in modern operations," },
            { pattern: /\bit\s+is\s+imperative\s+to\s+note\s+that,?\s*/gi, replacement: "notably, " },
            { pattern: /\bserves\s+as\s+a\s+testament\s+to\b/gi, replacement: "clearly demonstrates" },
            { pattern: /\bdelves\s+into\s+the\s+multifaceted(?:\s+nature\s+of)?\b/gi, replacement: "examines the various aspects of" },
            { pattern: /\bplays\s+a\s+pivotal\s+role\s+in\s+shaping\b/gi, replacement: "directly influences" },
            { pattern: /\bundeniably\s+highlights\s+the\s+significance\s+of\b/gi, replacement: "firmly emphasizes" },
            { pattern: /\bit\s+is\s+crucial\s+to\s+recognize\s+that\b/gi, replacement: "one key point is that" },
            { pattern: /\bfosters\s+an\s+environment\s+of\b/gi, replacement: "builds an atmosphere for" },
            { pattern: /\bby\s+leveraging\s+these\s+insights\b/gi, replacement: "applying these findings" },
            { pattern: /\bin\s+this\s+comprehensive\s+overview\b/gi, replacement: "across this review" },
            { pattern: /\bnavigating\s+the\s+complexities\s+of\b/gi, replacement: "managing the challenges of" },
            { pattern: /\ba\s+nuanced\s+understanding\s+of\b/gi, replacement: "a clear perspective on" },

            // 7. Anti-slop: 2026 detector updates (antislop-copywriting §Empty AI Vocabulary + §Rhythm)
            { pattern: /\bsynergy\b/gi, replacement: "collaboration" },
            { pattern: /\bsynergistic\b/gi, replacement: "collaborative" },
            { pattern: /\brobust\s+(?:framework|solution|approach|system)\b/gi, replacement: "reliable $1" },
            { pattern: /\brobust\b/gi, replacement: "solid" },
            { pattern: /\bproactive(?:ly)?\s+address(?:ing)?\b/gi, replacement: "directly addressing" },
            { pattern: /\bparadigm\s+shift\b/gi, replacement: "fundamental change" },
            { pattern: /\bnew\s+paradigm\b/gi, replacement: "new approach" },
            { pattern: /\bcomprehensive\s+and\s+holistic\b/gi, replacement: "thorough and integrated" },
            { pattern: /\bkey\s+takeaway\s+(?:here\s+)?is\s+that\b/gi, replacement: "the main point is" },
            { pattern: /\bit\s+is\s+worth\s+mentioning\s+that\b/gi, replacement: "notably," },
            { pattern: /\bprove\s+to\s+be\s+(?:a\s+)?(?:valuable|crucial|essential|vital)\b/gi, replacement: "turn out to be useful" },
            { pattern: /\bwhich\s+means\s+that,?\s*/gi, replacement: ". " },
            { pattern: /\band\s+it\s+is\s+also\s+worth\s+noting\s+that,?\s*/gi, replacement: ". Notably, " },
            { pattern: /\bright\s+and\s+proper\b/gi, replacement: "proper" },
            { pattern: /\beach\s+and\s+every\b/gi, replacement: "every" },
            { pattern: /\bfirst\s+and\s+foremost\b/gi, replacement: "first" },

            // Aphorism formulas (antislop-copywriting §Aphorism Formulas)
            { pattern: /\bX\s+is\s+the\s+new\s+Y\b/gi, replacement: "" },
            { pattern: /\bat\s+the\s+end\s+of\s+the\s+day,?\s*/gi, replacement: "ultimately, " },
            { pattern: /\bwhen\s+all\s+is\s+said\s+and\s+done,?\s*/gi, replacement: "ultimately, " },
            { pattern: /\bthe\s+bottom\s+line\s+is\s+that,?\s*/gi, replacement: "in short, " }
        ],

        toneReplacements: {
            academic: [
                { pattern: /\bvery\s+good\b/gi, replacement: "highly rigorous" },
                { pattern: /\bbig\s+issue\b/gi, replacement: "substantive problem" },
                { pattern: /\blot\s+of\b/gi, replacement: "substantial number of" },
                { pattern: /\bshows\s+clearly\b/gi, replacement: "empirically substantiates" }
            ],
            tuton: [
                { pattern: /\bin\s+my\s+humble\s+opinion\b/gi, replacement: "from my perspective" },
                { pattern: /\bas\s+discussed\s+in\s+the\s+module\b/gi, replacement: "as outlined in the course material" },
                { pattern: /\bit\s+can\s+be\s+concluded\s+that\b/gi, replacement: "the key takeaway is that" }
            ],
            formal: [
                { pattern: /\bwe\s+must\b/gi, replacement: "the team should" },
                { pattern: /\bget\s+back\s+to\b/gi, replacement: "follow up regarding" },
                { pattern: /\bmake\s+sure\b/gi, replacement: "ensure that" },
                { pattern: /\bbig\s+deal\b/gi, replacement: "critical priority" }
            ],
            casual: [
                { pattern: /\bconsequently,?\b/gi, replacement: "so basically," },
                { pattern: /\bfurthermore,?\b/gi, replacement: "plus," },
                { pattern: /\bnevertheless,?\b/gi, replacement: "still," },
                { pattern: /\butilize\b/gi, replacement: "use" },
                { pattern: /\bin\s+order\s+to\b/gi, replacement: "to" }
            ],
            journalistic: [
                { pattern: /\breports\s+indicate\s+that\b/gi, replacement: "field reports reveal" },
                { pattern: /\bit\s+is\s+reported\s+that\b/gi, replacement: "records indicate" },
                { pattern: /\bofficials\s+stated\s+that\b/gi, replacement: "authorities confirmed that" }
            ],
            creative: [
                { pattern: /\bin\s+a\s+vibrant\s+way\b/gi, replacement: "vividly alive" },
                { pattern: /\bvery\s+quiet\b/gi, replacement: "hushed and still" },
                { pattern: /\bas\s+time\s+went\s+by\b/gi, replacement: "with each passing day," }
            ],
            simple: [
                { pattern: /\b(?:it\s+can\s+be\s+said\s+that|at\s+the\s+present\s+moment)\b/gi, replacement: "" },
                { pattern: /\bhas\s+the\s+ability\s+to\b/gi, replacement: "can" },
                { pattern: /\bconduct\s+an\s+investigation\b/gi, replacement: "investigate" },
                { pattern: /\bgive\s+assistance\s+to\b/gi, replacement: "help" }
            ]
        },

        transitions: {
            academic: [
                "From a theoretical perspective,",
                "Empirically speaking,",
                "Upon closer examination,",
                "In practical terms,",
                "Methodologically,",
                "In this analytical framework,"
            ],
            tuton: [
                "From this case perspective,",
                "Looking at the course module,",
                "Importantly,",
                "In practical terms,"
            ],
            formal: [
                "In this regard,",
                "Operationally speaking,",
                "Moving forward,",
                "From an executive standpoint,",
                "Consequently,"
            ],
            casual: [
                "Honestly,",
                "Interestingly,",
                "Turns out,",
                "At the end of the day,",
                "If you look closely,"
            ],
            journalistic: [
                "Reports indicate,",
                "Crucially,",
                "Behind the scenes,",
                "Meanwhile,",
                "Current data reveals,"
            ],
            creative: [
                "Slowly but surely,",
                "Beneath the surface,",
                "Curiously enough,",
                "In plain sight,"
            ],
            simple: [
                "In short,",
                "Simply put,",
                "Because of this,",
                "Consequently,",
                "Essentially,"
            ]
        },

        // Tone-Specific Greetings & Openings
        openings: {
            academic: "Greetings to all academic colleagues and peers,",
            tuton: "Good day to the Tutor and fellow online students,",
            formal: "Dear esteemed partners and colleagues,",
            casual: "Hey everyone,",
            journalistic: "Editorial greetings,",
            creative: "Warmest greetings to fellow readers,",
            simple: "Hello,"
        },

        // Tone-Specific Closings & Sign-Offs
        closings: {
            academic: "Thus concludes this academic inquiry. May these observations contribute constructively to the scholarly discourse. Thank you.",
            tuton: "This concludes my response. I warmly welcome feedback and constructive guidance from the Tutor and peers. Thank you.",
            formal: "Respectfully submitted. We appreciate your consideration and continued collaboration. Thank you.",
            casual: "That's all from me for now, hope it helps! What are your thoughts on this?",
            journalistic: "This summarizes current verified field reports. Further updates will follow as developments unfold.",
            creative: "A quiet reflection left behind, hoping to offer a meaningful perspective along the journey.",
            simple: "Thank you."
        },

        samplePrompts: {
            tuton: "Allow me to share my perspective on this week's discussion forum topic regarding information systems planning. Based on the course materials and case study, prioritizing core software requirements while leveraging existing hardware is the most viable path forward.",
            academic: "Artificial intelligence has become a paramount technological breakthrough in today's fast-paced world. It is undeniable that machine learning models play a pivotal role in modern scientific inquiry. Furthermore, this serves as a testament to the power of computational algorithms. In conclusion, delving into these methodologies will foster innovation across interdisciplinary domains.",
            formal: "In light of the recent operational assessment, it is important to remember that inter-departmental synergy plays a crucial role in project success. Moreover, a comprehensive overview reveals notable efficiency gains. Moving forward, we recommend streamlined communication channels.",
            casual: "Exploring new tech trends in today's digital age can feel a bit overwhelming. But when you really delve into the details, you notice how much everyday tools have improved. In conclusion, embracing these changes makes everyday work a whole lot easier."
        }
    },

    es: {
        name: "Español",
        flag: "🇪🇸",
        cliches: [
            { pattern: /\s*—\s*/g, replacement: ", " },
            { pattern: /\ben conclusión,?\b/gi, replacement: "en última instancia," },
            { pattern: /\bes crucial destacar que\b/gi, replacement: "conviene señalar que" },
            { pattern: /\bjuega un papel fundamental\b/gi, replacement: "influye directamente" },
            { pattern: /\ben el mundo actual\b/gi, replacement: "hoy en día" },
            { pattern: /\bun testimonio de\b/gi, replacement: "prueba clara de" }
        ],
        transitions: {
            academic: ["Desde una perspectiva empírica,", "Resulta evidente que", "En este marco analítico,"],
            formal: ["Con respecto a esto,", "En términos operativos,", "De cara al futuro,"],
            casual: ["La verdad es que", "Al final de cuentas,", "Lo curioso es que"]
        },
        samplePrompts: {
            academic: "La inteligencia artificial desempeña un papel fundamental en el mundo actual. Es crucial destacar que los avances computacionales son un testimonio de la innovación. En conclusión, debemos profundizar en sus implicaciones éticas."
        }
    },

    fr: {
        name: "Français",
        flag: "🇫🇷",
        cliches: [
            { pattern: /\s*—\s*/g, replacement: ", " },
            { pattern: /\ben conclusion,?\b/gi, replacement: "en définitive," },
            { pattern: /\bil est crucial de noter que\b/gi, replacement: "soulignons que" },
            { pattern: /\bjoue un rôle primordial\b/gi, replacement: "pèse lourdement" },
            { pattern: /\bdans le monde d'aujourd'hui\b/gi, replacement: "de nos jours" }
        ],
        transitions: {
            academic: ["D'un point de vue analytique,", "Les observations suggèrent que", "De fait,"],
            formal: ["Dans cette optique,", "Sur le plan operational,", "Par conséquent,"],
            casual: ["Au fond,", "En réalité,", "Ce qui frappe surtout,"]
        },
        samplePrompts: {
            academic: "L'intelligence artificielle joue un rôle primordial dans le monde d'aujourd'hui. Il est crucial de noter ses répercussions méthodologiques. En conclusion, cette évolution redéfinit nos paradigmes de recherche."
        }
    },

    de: {
        name: "Deutsch",
        flag: "🇩🇪",
        cliches: [
            { pattern: /\s*—\s*/g, replacement: ", " },
            { pattern: /\bzusammenfassend lässt sich sagen\b/gi, replacement: "letztlich zeigt sich" },
            { pattern: /\bes ist von entscheidender bedeutung\b/gi, replacement: "wichtig ist" },
            { pattern: /\bspielt eine entscheidende rolle\b/gi, replacement: "ist maßgeblich" },
            { pattern: /\bin der heutigen zeit\b/gi, replacement: "heute" }
        ],
        transitions: {
            academic: ["Empirisch betrachtet,", "Dieser Befund verdeutlicht,", "Methodisch gesehen,"],
            formal: ["In diesem Zusammenhang,", "Aus betrieblicher Sicht,", "Dementsprechend,"],
            casual: ["Eigentlich,", "Unterm Strich,", "Interessanterweise,"]
        },
        samplePrompts: {
            academic: "Künstliche Intelligenz spielt eine entscheidende Rolle in der heutigen Zeit. Es ist von entscheidender Bedeutung, neue Modelle zu analysieren. Zusammenfassend lässt sich sagen, dass diese Technologie die Zukunft prägt."
        }
    }
};

/**
 * Extensive, Context-Safe Synonym and Collocation Knowledge Base (350+ Headwords)
 * Grouped strictly by Part-of-Speech and syntactic semantics to prevent ungrammatical collocations.
 */
const HUMANIZER_DICTIONARY = {
    id: {
        // --- VERBS (Kata Kerja Aksi, Analisis, Kognitif & Komunikasi) ---
        "mengubah": ["merombak", "mentransformasi", "memodifikasi", "menata ulang"],
        "meningkatkan": ["mengakselerasi", "memperkuat", "mengoptimalkan", "mendongkrak", "meningkatkan"],
        "menurunkan": ["mereduksi", "memangkas", "menekan", "mengurangi"],
        "mengembangkan": ["menumbuhkan", "memperluas", "memajukan", "menggarap"],
        "menciptakan": ["menghasilkan", "melahirkan", "membangun", "membentuk"],
        "menghasilkan": ["menelurkan", "membuahkan", "mencatatkan", "melahirkan"],
        "menggunakan": ["menerapkan", "memanfaatkan", "mengadopsi", "memberdayakan"],
        "memanfaatkan": ["mengoptimalkan", "menggunakan", "memaksimalkan", "mendayagunakan"],
        "memilih": ["memprioritaskan", "memilih", "menentukan pilihan pada"],
        "menentukan": ["mendikte", "mengendalikan", "memastikan", "menetapkan"],
        "mendorong": ["memacu", "merangsang", "menggerakkan", "menstimulasi"],
        "membantu": ["memudahkan", "menunjang", "menyokong", "meringankan"],
        "mengatasi": ["menyelesaikan", "mengurai", "menanggulangi", "menuntaskan"],
        "menjelaskan": ["menguraikan", "memaparkan", "menjabarkan", "menerangkan"],
        "menguraikan": ["membeberkan", "menjabarkan", "memaparkan"],
        "menganalisis": ["menelaah", "mengkaji", "membedah", "mengevaluasi"],
        "mengkaji": ["meneliti", "menelaah", "menyelidiki"],
        "meneliti": ["mengkaji", "menginvestigasi", "mengevaluasi"],
        "mengevaluasi": ["menguji", "menakar", "menilai", "menimbang"],
        "membuktikan": ["menegaskan", "memperjelas", "mengonfirmasi", "memperlihatkan"],
        "menunjukkan": ["memperlihatkan", "mencerminkan", "mengindikasikan", "mencatatkan"],
        "memahami": ["mencermati", "menyadari", "menangkap makna", "menyelami"],
        "mengetahui": ["menyadari", "mencermati", "mengenali"],
        "memicu": ["menyulut", "merangsang", "menimbulkan", "mendorong lahirnya"],
        "menyebabkan": ["mengakibatkan", "membuahkan", "memicu", "bermuara pada"],
        "mempengaruhi": ["berdampak pada", "mengendalikan", "mewarnai", "menentukan"],
        "membatasi": ["mengunci", "merestriksi", "mematok", "mengikat"],
        "memperkuat": ["memperkokoh", "memantapkan", "mengakselerasi", "meneguhkan"],
        "mempercepat": ["mengakselerasi", "memacu", "mempersingkat alur"],
        "mempertimbangkan": ["menimbang", "memperhitungkan", "mengalkulasi"],
        "memperhatikan": ["mencermati", "menyoroti", "mengatensi"],
        "mengabaikan": ["mengesampingkan", "melalaikan", "menomorduakan"],
        "menghadapi": ["menjumpai", "bertemu dengan", "berhadapan dengan"],
        "membutuhkan": ["memerlukan", "menuntut", "mengharuskan"],
        "menuntut": ["mengharuskan", "mewajibkan", "mendorong perlunya"],
        "menerima": ["mengakomodasi", "menyambut", "menampung"],
        "memberikan": ["menyediakan", "menghadirkan", "menyodorkan", "menawarkan"],
        "memperoleh": ["meraih", "mengantongi", "mencatatkan perolehan"],
        "mencapai": ["merengkuh", "meraih", "menggapai"],
        "berkembang": ["tumbuh pesat", "berevolusi", "meluas", "kian dinamis"],
        "bergerak": ["bergeser", "berpindah", "berfluktuasi"],
        "berjalan": ["bergulir", "berlangsung", "berproses"],
        "terjadi": ["berlangsung", "muncul", "tercipta"],
        "berfungsi": ["beroperasi", "bekerja", "berjalan semestinya"],
        "berperan": ["berandil", "berkontribusi", "turut menentukan"],
        "berbeda": ["kontras", "berlainan", "bervariasi"],
        "berubah": ["bergeser", "bertransformasi", "berganti aluan"],
        "belajar": ["mempelajari", "mendalami", "menekuni", "belajar"],
        "bekerja": ["bekerja", "beroperasi", "menjalankan tugas"],
        "melihat": ["mencermati", "memandang", "mengamati"],
        "mencari": ["menelusuri", "merumuskan", "memburu"],
        "memperbaiki": ["membenahi", "merestrukturisasi", "merevisi", "menyempurnakan"],
        "menjalankan": ["mengoperasikan", "mengimplementasikan", "melangsungkan", "memobilisasi"],
        "mengatur": ["menata", "mengelola", "meregulasi", "mengorkestrasi"],
        "memastikan": ["menjamin", "menggaransi", "memverifikasi", "menegaskan"],
        "mengidentifikasi": ["memetakan", "mengenali", "menemukan", "mendeteksi"],
        "merumuskan": ["menyusun", "memformulasikan", "merancang", "mengonsep"],
        "menerapkan": ["mengimplementasikan", "mengaplikasikan", "mempraktikkan", "memberlakukan"],
        "meninggalkan": ["mengesampingkan", "menanggalkan", "melepaskan"],
        "mengurangi": ["mereduksi", "memangkas", "menekan", "memperkecil"],
        "menambah": ["memperbesar", "mengembangkan", "memperbanyak", "mengakumulasi"],
        "mengawasi": ["memantau", "memonitor", "mengontrol", "mencermati alur"],
        "mengkoordinasikan": ["menyinkronkan", "menyelaraskan", "menghubungkan", "menjembatani"],
        "mempersiapkan": ["menyiapkan", "merancang", "mematangkan", "mengantisipasi"],
        "menghubungkan": ["mengaitkan", "menjembatani", "mengharmonisasikan", "mengintegrasikan"],
        "menyelesaikan": ["menuntaskan", "merampungkan", "mengakhiri", "memuntaskan"],
        "menghindari": ["mencegah", "menepis", "mengantisipasi", "menghindarkan diri dari"],
        "memperjelas": ["menerangkan", "mengelaborasi", "mempertajam", "mempertegas"],
        "mengajukan": ["menyodorkan", "mengemukakan", "menyampaikan", "menawarkan"],
        "membangun": ["membina", "mengonstruksi", "mendirikan", "mengembangkan"],
        "mempertahankan": ["menjaga konsistensi", "memelihara", "mengamankan", "merawat"],
        "memperbandingkan": ["mengomparasikan", "menandingkan", "menyejajarkan"],
        "menyerap": ["mengadopsi", "mengasimilasi", "mengakomodasi"],
        "memantau": ["memonitor", "mengamati secara berkala", "mengontrol"],
        "mengamati": ["mencermati", "meninjau", "memperhatikan"],
        "menilai": ["menakar", "mengestimasi", "mengukur", "mengevaluasi"],
        "menetapkan": ["memutuskan", "menggariskan", "mematok", "menentukan"],
        "mengukur": ["mengalkulasi", "menakar", "menguji skala", "mengkuantifikasi"],
        "mengindikasikan": ["menandakan", "memperlihatkan sinyal", "mencerminkan"],
        "mengklarifikasi": ["memperjelas", "mengurai keraguan", "meluruskan"],
        "merekrut": ["menjaring", "menerima", "menarik talenta"],
        "menyederhanakan": ["meringkas", "mempermudah alur", "mengefisienkan"],
        "mengalokasikan": ["mengarahkan", "menyalurkan", "membagikan pos"],
        "mendukung": ["menunjang", "menyokong", "menguatkan", "mendorong"],
        "menghambat": ["merintangi", "menahan laju", "mengganjal"],
        "mengantisipasi": ["menyiapkan mitigasi", "mencegah sejak dini", "mengantisipasi"],
        "mengarahkan": ["membimbing", "memandu", "mengorientasikan"],
        "menghimpun": ["mengumpulkan", "mengakomodasi", "mengompilasi"],
        "meringkas": ["memadatkan", "menyimpulkan", "mengabstraksi"],
        "memisahkan": ["memilah", "mengisolasi", "mendiferensiasi"],
        "menyatukan": ["mengintegrasikan", "memadukan", "mengonsolidasikan"],
        "menguji": ["menguji coba", "mengetes", "mengecek reliabilitas"],
        "memperbarui": ["mengaktualisasikan", "memodernisasi", "menyegarkan kembali"],
        "memprediksi": ["mengestimasi", "meramalkan", "memproyeksikan"],
        "menggambarkan": ["melukiskan", "mempresentasikan", "mencitrakan"],
        "menyepakati": ["menyetujui", "bermufakat atas", "mengonfirmasi konsensus"],

        // --- NOUNS (Kata Benda, Konsep, Sistem & Entitas) ---
        "masalah": ["kendala", "tantangan", "persoalan", "hambatan"],
        "kendala": ["hambatan", "rintangan", "persoalan teknis"],
        "tantangan": ["pekerjaan rumah", "ujian tersendiri", "dinamika tantangan"],
        "solusi": ["jalan keluar", "penyelesaian", "resolusi", "langkah taktis"],
        "metode": ["pendekatan", "kerangka kerja", "prosedur", "mekanisme"],
        "pendekatan": ["metodologi", "sudut pandang", "kerangka kerja"],
        "proses": ["tahapan", "alur", "rangkaian kerja", "mekanisme"],
        "hasil": ["temuan", "capaian", "luaran", "output nyata"],
        "dampak": ["implikasi", "pengaruh", "konsekuensi", "imbas"],
        "tujuan": ["sasaran", "orientasi", "arah capaian", "fokus utama"],
        "faktor": ["variabel", "parameter", "unsur", "faktor"],
        "alasan": ["pertimbangan", "alasan", "argumen", "dasar pemikiran"],
        "asumsi": ["premis", "anggapan", "asumsi"],
        "kondisi": ["situasi", "keadaan", "kondisi di lapangan"],
        "situasi": ["kondisi", "keadaan nyata", "konteks"],
        "peluang": ["kesempatan", "peluang", "potensi"],
        "potensi": ["peluang", "kemungkinan", "kapasitas", "potensi"],
        "konsep": ["gagasan", "kerangka konsep", "ide dasar"],
        "strategi": ["langkah terukur", "strategi", "pendekatan"],
        "efisiensi": ["efisiensi", "penghematan", "daya guna"],
        "kinerja": ["performa", "produktivitas", "kinerja"],
        "krusial": ["sangat menentukan", "mendasar", "vital", "kunci"],
        "kemampuan": ["kapabilitas", "kemampuan", "keahlian"],
        "kebutuhan": ["keperluan", "kebutuhan", "prioritas"],
        "kebijakan": ["regulasi", "aturan", "kebijakan"],
        "keberhasilan": ["pencapaian", "kesuksesan", "keberhasilan"],
        "kegagalan": ["kendala", "kegagalan", "hambatan"],
        "perkembangan": ["perkembangan", "pertumbuhan", "kemajuan"],
        "pergerakan": ["pergerakan", "fluktuasi", "dinamika"],
        "ketentuan": ["persyaratan", "ketentuan", "kaidah"],
        "kesimpulan": ["kesimpulan", "garis besar", "rangkuman"],
        "perusahaan": ["perusahaan", "korporasi", "organisasi"],
        "pekerja": ["pekerja", "tenaga kerja", "karyawan"],
        "mahasiswa": ["mahasiswa", "peserta didik", "pembelajar"],
        "masyarakat": ["warga", "masyarakat", "publik"],
        "pemerintah": ["pemerintah", "regulator", "otoritas"],
        "pasar": ["pasar", "bursa", "pasar"],
        "bisnis": ["bisnis", "sektor usaha", "dunia usaha"],
        "industri": ["industri", "sektor industri"],
        "layanan": ["layanan", "pelayanan", "fasilitas"],
        "kualitas": ["kualitas", "mutu", "standar"],
        "cara": ["cara", "pola", "metode"],
        "hal": ["hal", "aspek", "faktor"],
        "ilmu": ["wawasan", "pengetahuan", "keilmuan"],
        "keterampilan": ["keterampilan", "keahlian", "kompetensi"],
        "dunia": ["dunia", "ranah", "lingkup"],
        "waktu": ["waktu", "tempo", "durasi", "waktu"],
        "informasi": ["keterangan", "data faktual", "informasi", "wawasan"],
        "teknologi": ["perangkat teknologi", "sistem otomasi", "peranti digital"],
        "komunikasi": ["interaksi", "alur koordinasi", "penyampaian pesan"],
        "organisasi": ["kelembagaan", "institusi", "badan usaha", "entitas kerja"],
        "lingkungan": ["ekosistem", "ranah kerja", "lingkungan sekitar"],
        "struktur": ["kerangka", "tatanan", "hierarki", "bangunan sistem"],
        "sumber": ["rujukan", "fondasi", "akar data", "hulu informasi"],
        "peraturan": ["regulasi", "norma", "kaidah legal", "aturan main"],
        "tahapan": ["fase", "langkah", "tahapan alur", "termin"],
        "evaluasi": ["penilaian", "penelaahan mutu", "audit", "tinjauan kritis"],
        "risiko": ["ancaman", "potensi kerugian", "eksposur bahaya"],
        "anggaran": ["alokasi dana", "pos biaya", "kemampuan finansial"],
        "kapasitas": ["daya tampung", "daya dukung", "kapabilitas muat"],
        "perilaku": ["tindakan", "kebiasaan", "pola sikap", "respons"],
        "rekan": ["kolega", "rekan sejawat", "mitra"],
        "pendidikan": ["pembelajaran", "edukasi", "ranah akademik"],
        "penelitian": ["riset", "studi investigasi", "kajian ilmiah"],
        "kemajuan": ["akselerasi", "pertumbuhan pesat", "progres nyata"],
        "kelemahan": ["titik rentan", "kekurangan", "defisit performa"],
        "kelebihan": ["keunggulan", "nilai kompetitif", "keistimewaan"],
        "dasar": ["fondasi", "pijakan", "landasan berpijak"],
        "analisis": ["kajian", "telaah", "pembedahan data"],
        "pelaksanaan": ["implementasi", "penerapan di lapangan", "eksekusi"],
        "keputusan": ["ketetapan", "resolusi pilihan", "konklusi final"],
        "kategori": ["klasifikasi", "kelompok", "golongan"],
        "pola": ["tipologi", "kecenderungan", "pola ritme"],
        "tuntutan": ["keharusan", "kebutuhan mendesak", "mandat"],
        "variabel": ["faktor ukur", "indikator", "parameter ubah"],
        "indikator": ["tolok ukur", "sinyal penanda", "patokan evaluasi"],
        "cakupan": ["ruang lingkup", "domain", "jangkauan"],
        "interaksi": ["hubungan timbal balik", "kontak koordinasi"],
        "transaksi": ["pertukaran data", "alur niaga", "proses transaksi"],
        "efektivitas": ["keberdayagunaan", "ketepatan sasaran", "ketercapaian"],
        "keberlanjutan": ["kesinambungan", "kelangsungan jangka panjang"],
        "pelanggan": ["konsumen", "pengguna layanan", "klien"],
        "produk": ["komoditas", "barang jadi", "hasil olahan"],
        "komponen": ["unsur", "bagian pembentuk", "elemen"],
        "koordinasi": ["penyelarasan langkah", "kemitraan kerja", "sinkronisasi"],
        "persaingan": ["kompetisi", "dinamika pasar", "rivalitas usaha"],
        "komitmen": ["keseriusan janji", "dedikasi", "keteguhan prinsip"],
        "pelatihan": ["pemberdayaan", "asimilasi keterampilan", "kursus intensif"],
        "pemahaman": ["wawasan menyeluruh", "daya tangkap", "internalisasi"],

        // --- ADJECTIVES & ADVERBS (Kata Sifat & Keterangan) ---
        "penting": ["signifikan", "esensial", "utama", "krusial"],
        "sangat": ["amat", "cukup", "begitu", "teramat"],
        "efektif": ["optimal", "berdaya guna", "tepat sasaran", "aplikatif"],
        "efisien": ["hemat daya", "ringkas terukur", "tepat guna"],
        "relevan": ["kontekstual", "tepat guna", "aplikatif", "selaras"],
        "besar": ["substansial", "signifikan", "luas"],
        "kecil": ["minor", "terbatas", "relatif sedikit"],
        "cepat": ["cepat", "akseleratif", "singkat", "gesit"],
        "lambat": ["tertahan", "bertahap pelan", "lamban"],
        "jelas": ["terang", "gamblang", "eksplisit"],
        "nyata": ["konkret", "riil", "faktual"],
        "akurat": ["presisi", "terukur persis", "tepat"],
        "fleksibel": ["luwes", "adaptif", "mudah disesuaikan"],
        "ketat": ["kaku", "restriktif", "terbatas"],
        "stagnan": ["mendatar", "statis", "cenderung datar"],
        "fluktuatif": ["dinamis", "variatif", "berubah-ubah"],
        "banyak": ["sejumlah", "beragam", "berbagai", "kian banyak"],
        "sedikit": ["minim", "terbatas", "segelintir"],
        "sering": ["kerap", "lazim", "berulang kali"],
        "jarang": ["minim dijumpai", "tergolong langka"],
        "umumnya": ["pada umumnya", "lazimnya", "kebanyakan"],
        "khususnya": ["terutama", "utamanya", "lebih spesifik"],
        "langsung": ["langsung", "seketika", "tanpa perantara"],
        "bertahap": ["gradual", "berjenjang", "fase demi fase"],
        "mendalam": ["komprehensif", "seksama", "tuntas"],
        "sederhana": ["lugas", "ringkas", "mudah dipahami"],
        "rumit": ["kompleks", "berliku", "berlapis"],
        "positif": ["konstruktif", "menguntungkan", "bernilai tambah"],
        "negatif": ["kontraproduktif", "merugikan", "berisiko"],
        "baru": ["mutakhir", "anyar", "terkini"],
        "lama": ["terdahulu", "sebelumnya", "usang"],
        "tinggi": ["tinggi", "cukup tinggi", "tinggi"],
        "rendah": ["minim", "terbatas", "moderat"],
        "mudah": ["praktis", "mudah", "gampang"],
        "sulit": ["sukar", "penuh tantangan", "kompleks"],
        "pasti": ["niscaya", "sudah barang tentu", "terjamin"],
        "mungkin": ["berpotensi", "boleh jadi", "berpeluang"],
        "komprehensif": ["menyeluruh", "tuntas", "luas dan mendalam"],
        "terstruktur": ["rapi berpola", "sistematis", "tertata runut"],
        "transparan": ["terbuka", "akuntabel", "gamblang"],
        "konsisten": ["ajek", "terus-menerus", "berkelanjutan", "stabil"],
        "dinamis": ["bergerak luwes", "adaptif terhadap arus", "variatif"],
        "rasional": ["masuk akal", "logis", "dapat dipertanggungjawabkan"],
        "prioritas": ["keharusan utama", "fokus primer", "agenda pokok"],
        "akuntabel": ["dapat diverifikasi", "dapat dipertanggungjawabkan", "sahih"],
        "maksimal": ["optimal", "puncak capaian", "seutuhnya"],
        "minimal": ["paling sedikit", "ambang dasar", "sekurang-kurangnya"],
        "signifikan": ["berarti", "berpengaruh besar", "substansial"],
        "mendasar": ["fundamental", "pokok", "prinsipil"],
        "spesifik": ["khusus", "terperinci", "terfokus pada satu hal"],
        "objektif": ["faktual", "netral tanpa bias", "bebas pretensi"],
        "intensif": ["mendalam dan berulang", "terkonsentrasi penuh", "seksama"],
        "mandiri": ["otonom", "berdiri sendiri", "independen"],
        "berkelanjutan": ["langgeng", "berkesinambungan", "lestari"],
        "inklusif": ["merangkul semua", "terbuka luas", "menyeluruh"],
        "konkret": ["riil di lapangan", "nyata kasat mata", "faktual"],
        "ideal": ["paling tepat", "optimal", "patokan unggul"],
        "moderat": ["berimbang", "tidak berlebihan", "wajar"],
        "terbatas": ["minim ruang", "berbatas kuota", "sedikit"],
        "kritis": ["tajam menelaah", "analitis mendalam", "peka persoalan"],
        "strategis": ["bernilai kunci", "sangat menentukan posisi", "taktis"],
        "kompatibel": ["cocok berpadu", "selaras digunakan bersama", "serasi"],
        "inovatif": ["kreatif terobosan", "segar berbeda", "mutakhir"],
        "produktif": ["berdaya luaran tinggi", "berkinerja prima"],
        "kolaboratif": ["sinergis bersama", "gotong royong", "terpadu"],
        "valid": ["sahih", "terverifikasi benar", "dapat dipercaya"],
        "kredibel": ["terpercaya", "bereputasi baik", "dapat diandalkan"],
        "reliabel": ["andal diuji berulang", "konsisten hasilnya", "pasti"],
        "berkualitas": ["bermutu unggul", "berstandar tinggi"],
        "profesional": ["berintegritas tinggi", "cakap bertugas", "kompeten"],

        // --- CONNECTORS & DISCOURSE MARKERS ---
        "karena": ["lantaran", "sebab", "mengingat"],
        "sebab": ["karena", "lantaran", "sebab"],
        "tetapi": ["namun", "akan tetapi", "hanya saja"],
        "namun": ["akan tetapi", "hanya saja", "namun"],
        "meskipun": ["kendati", "walaupun", "sekalipun"],
        "walaupun": ["kendati", "meskipun", "walau"],
        "sehingga": ["sehingga", "alhasil", "akibatnya"],
        "akibatnya": ["dampaknya", "hasilnya", "akibatnya"],
        "selain": ["di samping", "selain", "terlepas dari"],
        "bahkan": ["malahan", "bahkan", "nyatanya"],
        "justru": ["malahan", "justru", "sebaliknya"],
        "artinya": ["maknanya", "dengan kata lain", "artinya"],
        "agar": ["supaya", "guna", "agar"],
        "supaya": ["agar", "supaya", "guna"],
        "untuk": ["guna", "untuk", "demi"],
        "bisa": ["dapat", "mampu", "bisa"],
        "dapat": ["bisa", "mampu", "dapat"],
        "harus": ["perlu", "wajib", "harus"],
        "hanya": ["sekadar", "semata", "hanya"],
        "sudah": ["telah", "sudah"],
        "telah": ["sudah", "kini", "telah"],
        "sedang": ["tengah", "sedang"],
        "masih": ["masih", "tetap", "terus"],
        "tetap": ["tetap", "masih", "konsisten"],
        "adapun": ["terkait hal itu,", "mengenai hal tersebut,", "sementara itu,"],
        "kendati": ["meskipun", "walaupun", "sekalipun"],
        "sedangkan": ["sementara itu,", "adapun", "di sisi lain,"],
        "padahal": ["kenyataannya,", "nyatanya,", "faktanya,"],
        "sementara": ["di waktu bersamaan,", "dalam waktu yang sama,", "sementara itu,"],
        "sebaliknya": ["justru sebaliknya,", "kontras dengan itu,", "malahan"],
        "terlebih": ["apalagi,", "khususnya,", "terutama sekali,"],
        "lagipula": ["di samping itu,", "tambahan pula,", "selain itu,"],
        "alhasil": ["dampaknya,", "hasilnya,", "akibatnya,"],
        "nyatanya": ["pada kenyataannya,", "faktanya,", "kenyataannya,"],
        "lazimnya": ["biasanya,", "secara umum,", "pada umumnya,"],
        "terkadang": ["pada saat tertentu,", "ada kalanya,", "sesekali"]
    },

    en: {
        // --- VERBS ---
        "change": ["transform", "modify", "alter", "reshape"],
        "increase": ["boost", "elevate", "accelerate", "expand"],
        "decrease": ["reduce", "curtail", "diminish", "scale down"],
        "develop": ["foster", "advance", "cultivate", "expand"],
        "create": ["generate", "craft", "produce", "establish"],
        "produce": ["yield", "deliver", "generate", "render"],
        "use": ["adopt", "deploy", "leverage", "utilize"],
        "choose": ["prioritize", "opt for", "favor", "select"],
        "determine": ["dictate", "shape", "govern", "establish"],
        "help": ["assist", "enable", "support", "streamline"],
        "solve": ["address", "resolve", "settle", "overcome"],
        "explain": ["clarify", "articulate", "elucidate", "detail"],
        "analyze": ["examine", "scrutinize", "assess", "evaluate"],
        "evaluate": ["assess", "appraise", "gauge", "weigh"],
        "prove": ["confirm", "validate", "substantiate", "affirm"],
        "show": ["demonstrate", "illustrate", "reflect", "indicate"],
        "understand": ["grasp", "perceive", "comprehend", "discern"],
        "cause": ["trigger", "prompt", "induce", "lead to"],
        "affect": ["impact", "influence", "shape", "alter"],
        "limit": ["constrain", "restrict", "bound", "narrow"],
        "strengthen": ["reinforce", "bolster", "fortify", "consolidate"],
        "accelerate": ["expedite", "speed up", "hasten", "quicken"],
        "consider": ["weigh", "deliberate", "take into account"],
        "require": ["necessitate", "demand", "call for", "mandate"],
        "obtain": ["acquire", "secure", "gain", "derive"],
        "achieve": ["attain", "accomplish", "reach", "realize"],
        "improve": ["refine", "upgrade", "enhance", "elevate"],
        "monitor": ["track", "observe", "oversee", "supervise"],
        "identify": ["pinpoint", "detect", "discern", "distinguish"],
        "formulate": ["devise", "frame", "craft", "articulate"],
        "implement": ["execute", "apply", "enforce", "put into practice"],
        "coordinate": ["align", "synchronize", "harmonize", "integrate"],
        "facilitate": ["streamline", "ease", "expedite", "promote"],

        // --- NOUNS ---
        "problem": ["hurdle", "challenge", "obstacle", "bottleneck"],
        "solution": ["resolution", "workaround", "remedy", "answer"],
        "method": ["framework", "approach", "procedure", "strategy"],
        "approach": ["methodology", "perspective", "stance"],
        "process": ["workflow", "pipeline", "progression", "mechanism"],
        "result": ["outcome", "finding", "output", "dividend"],
        "impact": ["implication", "repercussion", "consequence", "effect"],
        "goal": ["objective", "target", "milestone", "focus"],
        "factor": ["variable", "parameter", "driver", "component"],
        "reason": ["rationale", "foundation", "underlying basis", "driver"],
        "condition": ["state", "environment", "circumstance", "setting"],
        "opportunity": ["window", "prospect", "avenue", "opening"],
        "concept": ["framework", "premise", "construct", "notion"],
        "strategy": ["tactical plan", "roadmap", "blueprint", "scheme"],
        "efficiency": ["productivity", "streamlined execution", "output ratio"],
        "capacity": ["bandwidth", "capability", "threshold", "volume"],
        "framework": ["structure", "architecture", "scaffolding", "model"],
        "guideline": ["directive", "benchmark", "standard", "protocol"],
        "evaluation": ["assessment", "appraisal", "critique", "review"],
        "advantage": ["edge", "merit", "asset", "benefit"],

        // --- ADJECTIVES & ADVERBS ---
        "important": ["vital", "essential", "significant", "pivotal"],
        "effective": ["impactful", "productive", "functional", "potent"],
        "relevant": ["contextual", "pertinent", "applicable", "aligned"],
        "large": ["substantial", "considerable", "extensive", "broad"],
        "small": ["modest", "marginal", "minimal", "contained"],
        "rapid": ["swift", "prompt", "accelerated", "expedient"],
        "clear": ["evident", "transparent", "unambiguous", "distinct"],
        "accurate": ["precise", "exact", "calibrated", "rigorous"],
        "flexible": ["adaptable", "modular", "versatile", "pliant"],
        "complex": ["intricate", "layered", "multifaceted", "involved"],
        "simple": ["concise", "straightforward", "uncluttered", "direct"],
        "mainly": ["primarily", "predominantly", "chiefly", "largely"],
        "especially": ["notably", "in particular", "specifically"],
        "thoroughly": ["comprehensively", "rigorously", "meticulously"],
        "consistent": ["steady", "uniform", "unwavering", "reliable"],
        "strategic": ["tactical", "deliberate", "calculated", "decisive"],
        "substantial": ["meaningful", "appreciable", "weighty", "pronounced"],

        // --- CONNECTORS ---
        "because": ["given that", "since", "as", "owing to"],
        "however": ["nevertheless", "yet", "that said", "on the other hand"],
        "although": ["even though", "while", "despite the fact that"],
        "therefore": ["consequently", "thus", "accordingly", "as a result"],
        "besides": ["furthermore", "in addition to", "alongside"],
        "meanwhile": ["concurrently", "at the same time", "in the interim"],
        "similarly": ["likewise", "in a corresponding manner", "by the same token"]
    }
};

/**
 * Multi-Word Semantic Phrase Collocations & Idiomatic Equivalents ("Similar Means")
 * Targets 3-5 gram token sequences to completely break n-gram predictability in Turnitin, Drillbit, Copyleaks, and GPTZero.
 */
const SIMILAR_MEANS_DICTIONARY = {
    id: [
        { pattern: /\bdalam\s+rangka\s+mencapai\s+tujuan(?:\s+tersebut)?\b/gi, replacements: ["guna mewujudkan sasaran", "demi meraih target yang dituju", "untuk mencapai sasaran"] },
        { pattern: /\bmemiliki\s+pengaruh\s+yang\s+(?:sangat\s+)?signifikan\b/gi, replacements: ["berdampak nyata pada", "memberikan pengaruh terukur", "sangat menentukan arah"] },
        { pattern: /\bmengambil\s+langkah\s+konkret\b/gi, replacements: ["menjalankan aksi nyata", "menerapkan tindakan riil", "mengambil langkah taktis"] },
        { pattern: /\bberdasarkan\s+hasil\s+(?:penelitian|kajian|studi)\b/gi, replacements: ["merujuk temuan riset", "menilik hasil telaah", "berdasarkan data lapangan"] },
        { pattern: /\bmemberikan\s+kontribusi\s+(?:yang\s+)?positif\b/gi, replacements: ["turut membawa dampak baik", "berkontribusi secara nyata", "memberi nilai tambah"] },
        { pattern: /\bmempunyai\s+peranan\s+(?:yang\s+)?penting\b/gi, replacements: ["mengambil andil besar", "berperan aktif", "memegang posisi sentral"] },
        { pattern: /\bmenjadi\s+salah\s+satu\s+faktor\s+penentu\b/gi, replacements: ["turut menentukan keberhasilan", "menjadi variabel kunci", "menjadi penentu utama"] },
        { pattern: /\bperlu\s+dilakukan\s+evaluasi\s+berkala\b/gi, replacements: ["patut ditinjau secara berkala", "perlu dievaluasi bertahap", "layak dikaji berkesinambungan"] },
        { pattern: /\bdalam\s+upaya\s+mengoptimalkan\b/gi, replacements: ["demi mendongkrak performa", "guna memaksimalkan capaian", "agar berjalan optimal"] },
        { pattern: /\bmengalami\s+perkembangan\s+pesat\b/gi, replacements: ["tumbuh kian dinamis", "berkembang sangat akseleratif", "menunjukkan lompatan besar"] },
        { pattern: /\bmempunyai\s+korelasi\s+yang\s+erat\b/gi, replacements: ["berkaitan langsung dengan", "berjalan beriringan dengan", "berbanding lurus dengan"] },
        { pattern: /\bsejalan\s+dengan\s+perkembangan\s+zaman\b/gi, replacements: ["mengikuti dinamika masa kini", "menyesuaikan arus modernisasi", "selaras dengan kebutuhan saat ini"] },
        { pattern: /\bmemberikan\s+solusi\s+yang\s+efektif\b/gi, replacements: ["menghadirkan jalan keluar taktis", "memberikan penyelesaian aplikatif", "menjadi solusi tepat guna"] },
        { pattern: /\bmenghadapi\s+tantangan\s+yang\s+kompleks\b/gi, replacements: ["menjumpai persoalan berlapis", "berhadapan dengan kendala yang rumit", "menemui dinamika lapangan yang berat"] },
        { pattern: /\bpada\s+masa\s+yang\s+akan\s+datang\b/gi, replacements: ["di kemudian hari", "dalam jangka panjang ke depan", "pada masa mendatang"] },
        { pattern: /\bmembuka\s+peluang\s+baru\b/gi, replacements: ["memberi ruang kesempatan anyar", "membuka prospek baru", "menghadirkan peluang segar"] },
        { pattern: /\bdapat\s+diambil\s+kesimpulan\b/gi, replacements: ["garis besarnya,", "dapat dipastikan bahwa", "intinya,"] },
        { pattern: /\bmeningkatkan\s+efisiensi\s+dan\s+efektivitas(?:\s+kerja)?\b/gi, replacements: ["mengoptimalkan daya guna sekaligus hasil kerja", "memaksimalkan performa dan efisiensi kerja", "mewujudkan capaian kerja yang terukur"] },
        { pattern: /\bmengalokasikan\s+sumber\s+daya\b/gi, replacements: ["mengarahkan sarana dan dana", "membagi pos anggaran dan tenaga", "menyalurkan kapasitas operasional"] },
        { pattern: /\bsesuai\s+dengan\s+ketentuan\s+yang\s+berlaku\b/gi, replacements: ["mengikuti kaidah regulasi terkini", "patuh pada pedoman resmi", "selaras dengan aturan normatif"] },
        { pattern: /\bmengidentifikasi\s+permasalahan\s+utama\b/gi, replacements: ["memetakan akar persoalan", "menemukan titik simpul kendala", "merumuskan fokus masalah"] },
        { pattern: /\bmenjadi\s+tolok\s+ukur\s+utama\b/gi, replacements: ["menjadi barometer kunci", "dijadikan parameter rujukan", "menjadi standar penilaian primer"] },
        { pattern: /\bmelakukan\s+peninjauan\s+kembali\b/gi, replacements: ["mengevaluasi ulang", "meninjau kembali arah kebijakan", "mengoreksi catatan terdahulu"] },
        { pattern: /\bmempertimbangkan\s+berbagai\s+aspek\b/gi, replacements: ["menimbang sudut pandang menyeluruh", "melihat persoalan dari berbagai dimensi", "memperhitungkan aspek multiperspektif"] },
        { pattern: /\bmengambil\s+keputusan\s+yang\s+tepat\b/gi, replacements: ["menetapkan langkah presisi", "menentukan pilihan secara matang", "menarik kesimpulan strategis"] },
        { pattern: /\bmencapai\s+hasil\s+yang\s+optimal\b/gi, replacements: ["memperoleh capaian maksimal", "meraih luaran terbaik", "menghasilkan kinerja prima"] },
        { pattern: /\bberfungsi\s+sebagai\s+landasan\b/gi, replacements: ["menjadi pijakan mendasar", "berperan sebagai fondasi pokok", "menjadi tumpuan utama"] },
        { pattern: /\bmenunjukkan\s+kecenderungan\s+bahwa\b/gi, replacements: ["memperlihatkan indikasi kuat bahwa", "memberi sinyal jelas bahwa", "mengarahkan pada pola bahwa"] },
        { pattern: /\bmemberikan\s+kemudahan\s+bagi\b/gi, replacements: ["mempermudah langkah", "memberikan akses leluasa bagi", "meringankan beban"] },
        { pattern: /\bberada\s+pada\s+posisi\s+yang\s+strategis\b/gi, replacements: ["menempati posisi sentral", "memiliki peran kunci", "berdiri di titik strategis"] },
        { pattern: /\bmendapatkan\s+perhatian\s+khusus\b/gi, replacements: ["menjadi sorotan penting", "disorot secara mendalam", "diprioritaskan penanganannya"] },
        { pattern: /\bmelakukan\s+adaptasi\s+terhadap\b/gi, replacements: ["menyesuaikan diri dengan", "beradaptasi luwes pada", "menyelaraskan langkah dengan"] },
        { pattern: /\bmeminimalisir\s+risiko\s+yang\s+mungkin\s+terjadi\b/gi, replacements: ["menekan potensi bahaya", "mereduksi potensi kerugian", "memitigasi risiko di lapangan"] },
        { pattern: /\bmengoptimalkan\s+potensi\s+yang\s+ada\b/gi, replacements: ["mendayagunakan seluruh kapasitas yang tersedia", "menggali kapasitas laten", "memaksimalkan daya dukung"] },
        { pattern: /\bterdapat\s+perbedaan\s+yang\s+mencolok\b/gi, replacements: ["tampak kontras yang nyata", "terlihat jurang pemisah yang lebar", "terlihat divergensi yang kentara"] },
        { pattern: /\bberdasarkan\s+pertimbangan\s+tersebut\b/gi, replacements: ["menimbang rangkaian hal itu", "berangkat dari telaah tersebut", "melihat pertimbangan tadi"] },
        { pattern: /\bmembawa\s+perubahan\s+yang\s+signifikan\b/gi, replacements: ["memicu transformasi nyata", "merombak pola lama secara menyeluruh", "menghadirkan babak baru"] },
        { pattern: /\bmenuntut\s+adanya\s+kolaborasi\b/gi, replacements: ["mendorong perlunya kerja sama erat", "membutuhkan sinergi nyata", "mengharuskan keterlibatan bersama"] },
        { pattern: /\bmewujudkan\s+tata\s+kelola\s+yang\s+baik\b/gi, replacements: ["membangun sistem kelola yang akuntabel", "menerapkan tata laksana yang transparan", "menegakkan tata kelola terpercaya"] },
        { pattern: /\bmemperkuat\s+daya\s+saing\b/gi, replacements: ["meningkatkan keunggulan kompetitif", "mempertajam kapabilitas tanding", "mengukuhkan posisi di bursa"] }
    ,

            // 2026 Batch — collocations flagged by Turnitin, Drillbit, GPTZero AI writing patterns
            { pattern: /\bperlu\s+dilakukan\s+evaluasi\b/gi, replacements: ["perlu dievaluasi secara berkala", "harus dikaji ulang", "perlu ditinjau kembali"] },
            { pattern: /\bsangat\s+berperan\s+penting\b/gi, replacements: ["memegang peran kunci", "punya andil besar", "berpengaruh langsung"] },
            { pattern: /\bhal\s+ini\s+membuktikan\b/gi, replacements: ["ini memperlihatkan", "kondisi ini mengonfirmasi", "fakta ini menunjukkan"] },
            { pattern: /\btidak\s+bisa\s+dilepaskan\s+dari\b/gi, replacements: ["sangat terkait erat dengan", "tidak terpisahkan dari", "berkaitan langsung dengan"] },
            { pattern: /\bmembutuhkan\s+perhatian\s+(?:lebih|khusus)\b/gi, replacements: ["perlu dicermati lebih lanjut", "butuh perhatian ekstra", "layak mendapat prioritas"] },
            { pattern: /\bsangat\s+diperlukan\s+dalam\b/gi, replacements: ["menjadi kebutuhan mendasar di", "krusial keberadaannya dalam", "mutlak diperlukan dalam"] },
            { pattern: /\bdengan\s+cara\s+yang\s+efektif\b/gi, replacements: ["secara efektif", "dengan cara yang tepat sasaran", "dengan pendekatan yang teruji"] },
            { pattern: /\bupaya\s+peningkatan\s+kualitas\b/gi, replacements: ["langkah perbaikan kualitas", "ikhtiar meningkatkan mutu", "dorongan untuk memperbaiki kualitas"] },
            { pattern: /\bsebagai\s+salah\s+satu\s+solusi\b/gi, replacements: ["sebagai salah satu opsi", "sebagai pendekatan yang relevan", "sebagai alternatif yang layak dipertimbangkan"] },
            { pattern: /\bdalam\s+proses\s+pembelajaran\b/gi, replacements: ["dalam alur belajar", "saat menjalani proses belajar", "dalam tahapan pembelajaran"] },
            { pattern: /\bmemiliki\s+dampak\s+yang\s+signifikan\b/gi, replacements: ["berdampak nyata", "memberikan pengaruh yang cukup besar", "punya dampak yang tak kecil"] },
            { pattern: /\bdapat\s+disimpulkan\s+bahwa\b/gi, replacements: ["garis besarnya,", "intinya,", "dari sini terlihat bahwa"] }],
    en: [
        { pattern: /\bin\s+order\s+to\s+achieve\s+the\s+desired\s+outcome\b/gi, replacements: ["to reach the intended goal", "so as to attain targeted results", "to secure optimal findings"] },
        { pattern: /\bplays\s+an\s+indispensable\s+role\b/gi, replacements: ["is central to success", "serves as a vital factor", "holds a cornerstone position"] },
        { pattern: /\bsheds\s+light\s+on\s+the\s+fact\s+that\b/gi, replacements: ["clearly demonstrates that", "underscores that", "reveals that"] },
        { pattern: /\bin\s+the\s+current\s+fast-paced\s+environment\b/gi, replacements: ["under modern operational conditions", "in today's active climate", "amid rapid operational shifts"] },
        { pattern: /\bhas\s+a\s+direct\s+bearing\s+on\b/gi, replacements: ["substantially shapes", "directly steers", "strongly dictates"] },
        { pattern: /\btake\s+into\s+serious\s+consideration\b/gi, replacements: ["carefully evaluate", "closely weigh", "give thoughtful weight to"] },
        { pattern: /\byield\s+substantial\s+improvements\b/gi, replacements: ["deliver tangible gains", "produce measurable progress", "drive concrete enhancements"] },
        { pattern: /\bpaves\s+the\s+way\s+for\b/gi, replacements: ["opens opportunities for", "sets the foundation for", "creates viable avenues for"] },
        { pattern: /\bconduct\s+a\s+thorough\s+examination\b/gi, replacements: ["closely investigate", "rigorously scrutinize", "carefully dissect"] },
        { pattern: /\bat\s+the\s+present\s+point\s+in\s+time\b/gi, replacements: ["currently", "presently", "at this stage"] }
    ]
};

const COMMON_AI_PATTERNS = [
    /\b(furthermore|moreover|in conclusion|delve|testament|pivotal|beacon|tapestry|holistic|synergy|paramount|underscores|notably)\b/gi,
    /\b(merupakan hal yang|sangat krusial|tidak dapat dipungkiri|kesimpulannya|menyelami|memegang peranan penting|komprehensif|bukti nyata)\b/gi
];

if (typeof window !== 'undefined') {
    window.LANGUAGES = LANGUAGES;
    window.HUMANIZER_DICTIONARY = HUMANIZER_DICTIONARY;
    window.SIMILAR_MEANS_DICTIONARY = SIMILAR_MEANS_DICTIONARY;
    window.COMMON_AI_PATTERNS = COMMON_AI_PATTERNS;
}
